"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hwmux_client
from hwmux_client.model.patched_device_serializer_with_permissions import PatchedDeviceSerializerWithPermissions


class TestPatchedDeviceSerializerWithPermissions(unittest.TestCase):
    """PatchedDeviceSerializerWithPermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedDeviceSerializerWithPermissions(self):
        """Test PatchedDeviceSerializerWithPermissions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedDeviceSerializerWithPermissions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
