[tool.poetry]
name = "vigilant-crypto-snatch"
version = "4.4.0"
description = "Crypto currency buying agent"
authors = ["Martin Ueding <mu@martin-ueding.de>"]
license = "MIT"

[tool.poetry.scripts]
vigilant-crypto-snatch = "vigilant_crypto_snatch.cli:main"

[tool.poetry.dependencies]
BitstampClient = "^2.2.8"
appdirs = "^1.4.4"
coloredlogs = "^15.0"
pandas = { version = "^1.2.3", optional = true }
python = "^3.7.1,<3.10"
pyyaml = "^5.4.1"
requests = "^2.25.1"
scipy = {version = "^1.6.2", optional = true}
sqlalchemy = "^1.3.23"
streamlit = {version = "^0.84.0", optional = true}
urllib3 = "^1.26.3"
altair = {version = "^4.1.0", optional = true}
krakenex = "^2.1.0"
python-dateutil = "^2.8.2"

[tool.poetry.extras]
evaluation = ["pandas", "scipy", "streamlit", "altair"]

[tool.poetry.dev-dependencies]
black = "^21.6b0"
mkdocs_material = "^7.0.5"
pytest = "^6.2.2"
coverage = "^5.5"
pandas = "^1.2.4"
scipy = "^1.6.3"
streamlit = "^0.84.0"
altair = "^4.1.0"
pre-commit = "^2.13.0"
mypy = "^0.910"
types-PyYAML = "^5.4.6"
types-requests = "^2.25.6"
types-python-dateutil = "^0.1.6"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.mypy]
ignore_missing_imports = true
