
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T12:14:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "77ddcb523455db966e2737d195bc2dbbd5c75b69",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
