[tool.poetry]
name = "transpi"
version = "0.4.0"
description = "Transpi is a translation tool"
authors = ["ischaojie <zhuzhezhe95@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
requests-html = "^0.10.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
