
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T09:29:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1f08cd680cf322cc400fa6a0245610616b17b8e",
 "version": "2555"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
