[tool.poetry]
name = "autohooks-plugin-insert-license"
version = "0.1.3"
description = "An autohooks plugin to insert license in files with insert_license"
authors = ["Vincent Texier <vit@free.fr>"]
license = "GPL-3.0-or-later"
packages = [
  { include = "autohooks" },
]
keywords = [
  "git",
  "hooks",
  "insert_license",
]

[tool.poetry.dependencies]
python = "^3.7.0"
autohooks = "^21.7.0"

[tool.poetry.dev-dependencies]
black = "20.8b1"
pylint = "^2.6.0"
isort = "^5.9.3"
pre-commit-hooks = {git = "https://github.com/Lucas-C/pre-commit-hooks"}
autohooks-plugin-black = "^21.7.1"
autohooks-plugin-pylint = "^21.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autohooks]
mode = "poetry"
pre-commit = [
    "autohooks.plugins.black",
    "autohooks.plugins.pylint"
]

[tool.isort]
profile = "black"
