# coding: utf-8

"""
    BAPP API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.inline_response2009_transactions import InlineResponse2009Transactions  # noqa: E501
from bapp_api_client.rest import ApiException


class TestInlineResponse2009Transactions(unittest.TestCase):
    """InlineResponse2009Transactions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009Transactions(self):
        """Test InlineResponse2009Transactions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.inline_response2009_transactions.InlineResponse2009Transactions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
