
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-04T10:10:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5574fde4d198afd6a1a83d22b24fdaa63d53d64d",
 "version": "2021.11.04"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
