#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

package_dir = \
{'': 'src'}

setup(name='qtile-profiles',
      version='0.1.2',
      description='A profile manger for qtile',
      author=None,
      author_email='Paul Hoffmann <phfn@phfn.de>',
      url=None,
      py_modules=['qtile_profiles'],
      package_dir=package_dir,
     )
