
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-10T04:33:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "489afe595d0c80c5037abbfba795b571e6411340",
 "version": "1.15.0.post.dev436"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
