[package]
name = "pylylabel"
version = "3.0.2"
authors = ["Stephan Hügel <urschrei@gmail.com>", "Andy Wang <cbeuw.andy@gmail.com>"]
description = "A Rust implementation of the Polylabel algorithm for finding optimum polygon label positions, with Python binding."
readme = "README.md"
keywords = ["geo", "polylabel", "gis"]
license = "MIT"
edition = "2018"

[dependencies]
geo = "0.18.0"
num-traits = "0.2.8"
thiserror = "1.0.4"

[dev-dependencies]
criterion = "0.3.0"

[dependencies.pyo3]
version = "0.15.0"
features = ["extension-module"]

[lib]
name = "pylylabel"
crate-type = ["rlib", "cdylib"]
test = true
doctest = true
doc = true

[profile.release]
rpath = true
lto = true

[[bench]]
name = "benchmark"
harness = false

