[tool.poetry]
name = "cipher_ky2458"
version = "0.1.1"
description = "Each letter is replaced by a letter some fixed number of positions down the alphabet."
authors = ["Kun Yao"]
license = "MIT"
readme = "README.md"
documentation = 'https://cipher-kun-yao.readthedocs.io/en/latest/'
homepage = "https://github.com/QMSS-G5072-2021/cipher_kun_yao"
repository = "https://github.com/QMSS-G5072-2021/cipher_kun_yao"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.4"

[tool.poetry.dev-dependencies]
myst-nb = "^0.13.1"
sphinx-autoapi = "^1.8.4"
sphinx-rtd-theme = "^1.0.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
