# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QSequencerFrame.ui',
# licensing of 'QSequencerFrame.ui' applies.
#
# Created: Mon Jan 14 10:58:44 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_sequencerFrame(object):
    def setupUi(self, sequencerFrame):
        sequencerFrame.setObjectName("sequencerFrame")
        sequencerFrame.resize(1385, 681)
        sequencerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        sequencerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(sequencerFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(sequencerFrame)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.sequenceFrame = QtWidgets.QFrame(self.splitter)
        self.sequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sequenceFrame.setObjectName("sequenceFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sequenceFrame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.sequenceFrame)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.importLabel = QtWidgets.QLabel(self.layoutWidget)
        self.importLabel.setObjectName("importLabel")
        self.verticalLayout_2.addWidget(self.importLabel)
        self.importListView = ImportListView(self.layoutWidget)
        self.importListView.setAcceptDrops(True)
        self.importListView.setDragEnabled(True)
        self.importListView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.importListView.setAlternatingRowColors(True)
        self.importListView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.importListView.setObjectName("importListView")
        self.verticalLayout_2.addWidget(self.importListView)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.variableLabel = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variableLabel.sizePolicy().hasHeightForWidth())
        self.variableLabel.setSizePolicy(sizePolicy)
        self.variableLabel.setObjectName("variableLabel")
        self.verticalLayout_5.addWidget(self.variableLabel)
        self.variableTabWidget = QtWidgets.QTabWidget(self.layoutWidget_2)
        self.variableTabWidget.setObjectName("variableTabWidget")
        self.propertyTab = QtWidgets.QWidget()
        self.propertyTab.setObjectName("propertyTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.propertyTab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.variableTableWidget = VariableTableWidget(self.propertyTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variableTableWidget.sizePolicy().hasHeightForWidth())
        self.variableTableWidget.setSizePolicy(sizePolicy)
        self.variableTableWidget.setObjectName("variableTableWidget")
        self.verticalLayout_10.addWidget(self.variableTableWidget)
        self.variableTabWidget.addTab(self.propertyTab, "")
        self.limitTab = QtWidgets.QWidget()
        self.limitTab.setObjectName("limitTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.limitTab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.variableTabWidget.addTab(self.limitTab, "")
        self.optimizationTab = QtWidgets.QWidget()
        self.optimizationTab.setObjectName("optimizationTab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.optimizationTab)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.variableTabWidget.addTab(self.optimizationTab, "")
        self.verticalLayout_5.addWidget(self.variableTabWidget)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sequenceLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.sequenceLabel.setObjectName("sequenceLabel")
        self.verticalLayout_6.addWidget(self.sequenceLabel)
        self.sequenceTreeView = SequenceTreeView(self.layoutWidget_3)
        self.sequenceTreeView.setMouseTracking(False)
        self.sequenceTreeView.setAcceptDrops(True)
        self.sequenceTreeView.setDragEnabled(True)
        self.sequenceTreeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.sequenceTreeView.setHeaderHidden(True)
        self.sequenceTreeView.setObjectName("sequenceTreeView")
        self.verticalLayout_6.addWidget(self.sequenceTreeView)
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.previewTabWidget = QtWidgets.QTabWidget(sequencerFrame)
        self.previewTabWidget.setObjectName("previewTabWidget")
        self.horizontalLayout.addWidget(self.previewTabWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(sequencerFrame)
        self.variableTabWidget.setCurrentIndex(0)
        self.previewTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(sequencerFrame)

    def retranslateUi(self, sequencerFrame):
        sequencerFrame.setWindowTitle(QtWidgets.QApplication.translate("sequencerFrame", "Frame", None, -1))
        self.importLabel.setText(QtWidgets.QApplication.translate("sequencerFrame", "Imports:", None, -1))
        self.variableLabel.setText(QtWidgets.QApplication.translate("sequencerFrame", "Variables:", None, -1))
        self.variableTabWidget.setTabText(self.variableTabWidget.indexOf(self.propertyTab), QtWidgets.QApplication.translate("sequencerFrame", "Properties", None, -1))
        self.variableTabWidget.setTabText(self.variableTabWidget.indexOf(self.limitTab), QtWidgets.QApplication.translate("sequencerFrame", "Limits", None, -1))
        self.variableTabWidget.setTabText(self.variableTabWidget.indexOf(self.optimizationTab), QtWidgets.QApplication.translate("sequencerFrame", "Optimization", None, -1))
        self.sequenceLabel.setText(QtWidgets.QApplication.translate("sequencerFrame", "Sequence:", None, -1))

from sknrf.view.desktop.sequencer.widgets import ImportListView, VariableTableWidget, SequenceTreeView
