from pydantic import BaseModel


class TsTick(BaseModel):
    TsCode = ''
    Name = ''
    TradeTime = ''
    PrePrice = ''
    Price = ''
    Open = ''
    High = ''
    Low = ''
    Close = ''
    OpenInt = ''
    Volume = ''
    Amount = ''
    Num = ''
    AskPrice1 = ''
    AskVolume1 = ''
    BidPrice1 = ''
    BidVolume1 = ''
    AskPrice2 = ''
    AskVolume2 = ''
    BidPrice2 = ''
    BidVolume2 = ''
    AskPrice3 = ''
    AskVolume3 = ''
    BidPrice3 = ''
    BidVolume3 = ''
    AskPrice4 = ''
    AskVolume4 = ''
    BidPrice4 = ''
    BidVolume4 = ''
    AskPrice5 = ''
    AskVolume5 = ''
    BidPrice5 = ''
    BidVolume5 = ''
    AskPrice6 = ''
    AskVolume6 = ''
    BidPrice6 = ''
    BidVolume6 = ''
    AskPrice7 = ''
    AskVolume7 = ''
    BidPrice7 = ''
    BidVolume7 = ''
    AskPrice8 = ''
    AskVolume8 = ''
    BidPrice8 = ''
    BidVolume8 = ''
    AskPrice9 = ''
    AskVolume9 = ''
    BidPrice9 = ''
    BidVolume9 = ''
    AskPrice10 = ''
    AskVolume10 = ''
    BidPrice10 = ''
    BidVolume10 = ''


class TsTickIdx(BaseModel):
    TsCode = ''
    Name = ''
    TradeTime = ''
    Price = ''
    PrePrice = ''
    Open = ''
    High = ''
    Low = ''
    Volume = ''
    Amount = ''


class TsTickOpt(BaseModel):
    TsCode = ''
    InstrumentID = ''
    TradeTime = ''
    PrePrice = ''
    Price = ''
    Open = ''
    High = ''
    Low = ''
    Close = ''
    OpenInt = ''
    Volume = ''
    Amount = ''
    Num = ''
    AskPrice1 = ''
    AskVolume1 = ''
    BidPrice1 = ''
    BidVolume1 = ''
    PreDelta = ''
    CurrDelta = ''
    DifPrice1 = ''
    DifPrice2 = ''
    HighLimitPrice = ''
    LowLimitPrice = ''
    ReferPrice = ''


class TsTickFuture(BaseModel):
    TsCode = ''
    InstrumentID = ''
    TradeTime = ''
    PrePrice = ''
    Price = ''
    Open = ''
    High = ''
    Low = ''
    Close = ''
    OpenInt = ''
    Volume = ''
    Amount = ''
    Num = ''
    AskPrice1 = ''
    AskVolume1 = ''
    BidPrice1 = ''
    BidVolume1 = ''
    PreDelta = ''
    CurrDelta = ''
    DifPrice1 = ''
    DifPrice2 = ''
    HighLimitPrice = ''
    LowLimitPrice = ''
    ReferPrice = ''
    PreSettlePrice = ''
    SettlePrice = ''
