
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-06T13:48:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a62f2a900f1c4ac65dfcff92bbeba67fab1bf744",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
