[tool.poetry]
name = "python_csv_json_converter"
version = "0.1.4"
description = "Convert csv to Json. For learning purposes"
authors = ["Felipe França <felipejonataoliveira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.4"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
mypy = "^0.910"
black = "^21.9b0"
isort = "^5.9.3"
pandas-stubs = "^1.2.0"
ipython = "^7.28.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length=99

[tool.isort]
profile="black"

[tool.poetry.scripts]
csv_converter = 'python_csv_json_converter.converter:converter'