# coding: utf-8

"""
    BAPP API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.inline_response200121_active_timesheet import InlineResponse200121ActiveTimesheet  # noqa: E501
from bapp_api_client.rest import ApiException


class TestInlineResponse200121ActiveTimesheet(unittest.TestCase):
    """InlineResponse200121ActiveTimesheet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200121ActiveTimesheet(self):
        """Test InlineResponse200121ActiveTimesheet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.inline_response200121_active_timesheet.InlineResponse200121ActiveTimesheet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
