[tool.poetry]
name = "rlmate"
version = "0.0.6"
description = "tbd."
authors = [
    "Timo P. Gros <timopgros@cs.uni-saarland.de>", 
    "Joschka Groß <jgross@cs.uni-saarland.de>",     
]
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "*"
torch = "*"
GitPython = "^3.1.24"
pandas = "^1.3.4"
matplotlib = "^3.4.3"
leb128 = "^1.0.4"
python-telegram-bot = "^13.6"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.2"
pep8-naming = "^0.9.1"

[tool.poetry.scripts]
hermes = "rlmate.hermes:main"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

