
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9e72a9e1cbef494ef1f2d1104322edc8d7284092",
 "version": "2021.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
