- name: Disable logrotate
  service:
    name: logrotate
    enabled: no
    state: stopped

- name: Disable logrotate.timer
  service:
    name: logrotate.timer
    enabled: no
    state: stopped

- name: Use CI package cache to speed things up
  copy:
    content: |
      Acquire::http::Proxy "http://192.168.1.50:8000";
    dest: /etc/apt/apt.conf.d/00proxy
    owner: root
    group: root
    mode: u=r,g=r,o=r

- name: apt-get dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

# TODO(mikal): dial this back once we have things working.
- name: Install dependencies
  apt:
    name:
      [
        git,
        python3-dev,
        python3-grpcio,
        python3-pip,
        python3-venv,
        python3-wheel,
        python3,
        pwgen,
        tox,
      ]
    state: latest

- name: Copy server wheel file
  copy:
    src: "{{source_path}}/shakenfist/dist/{{hostvars['localhost']['server_wheel_file']}}"
    dest: "/tmp/{{hostvars['localhost']['server_wheel_file']}}"

- name: Make venv and install server wheel
  shell: |
    python3 -m venv --system-site-packages /srv/shakenfist/venv
    /srv/shakenfist/venv/bin/pip install -U pip
    /srv/shakenfist/venv/bin/pip install /tmp/shakenfist*whl
