repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "7eb0512c687ed3502fea11bae9b5ad0f657eb8ef"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hakancelik96/unimport
    rev: 2875c033c00877b6797f3a05761c7c7fe9aae46c
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]
  - repo: https://github.com/pycqa/isort
    rev: "995e016b9d888fea02bedeb5be8ea7f01b694b58"
    hooks:
      - id: isort
        files: "gdsfactory/.*"
        args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: 2b2f0c74acdb3de316e23ceb7dd0d7945c354050
  #   hooks:
  #     - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: "37861b4ce264f16754f4459d19522a05844daf9f"
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 142b2a1728520b478c7b8ce3b32f7826a2608fee
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.9b0]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "637a6a2084feaca229beb530ca12f12047f8ddce"
    hooks:
      - id: flake8
  - repo: https://github.com/kynan/nbstripout
    rev: 3843f5f7c586fa6f0df81423f35d52e6af8e3039
    hooks:
      - id: nbstripout
        files: ".ipynb"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "214c33306afe17f1cc7d2d55e4da705b6ebe0627"
  #   hooks:
  #     - id: mypy
  #       exclude: ^(docs/|example-plugin/|tests/fixtures)
  #       additional_dependencies:
  #         - "pydantic"

  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: master
  #   hooks:
  #       - id: darglint
  #
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: ""
  #   hooks:
  #       - id: pydocstyle
