# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\test-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2021-11-03 14:32:16.173727
__version__ = '3.2.3'