[tool.poetry]
name = "entity"
version = "0.1.0"
description = ""
authors = ["tactik8 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
tabulate = "^0.8.9"
cleanco = "^2.1"
email-normalize = "^2.0.0"
phonenumbers = "^8.12.36"
pycountry = "^20.7.3"
url-normalize = "^1.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
