
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T11:50:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "30ead4c954e0fb0c8b279914e97a9f243205b4a0",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
