# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QPreviewPlotFrame.ui',
# licensing of 'QPreviewPlotFrame.ui' applies.
#
# Created: Sat Jan 12 20:04:25 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_previewPlotFrame(object):
    def setupUi(self, previewPlotFrame):
        previewPlotFrame.setObjectName("previewPlotFrame")
        previewPlotFrame.resize(713, 797)
        previewPlotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        previewPlotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(previewPlotFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.previewPlot = ContentFigure(previewPlotFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.previewPlot.sizePolicy().hasHeightForWidth())
        self.previewPlot.setSizePolicy(sizePolicy)
        self.previewPlot.setObjectName("previewPlot")
        self.verticalLayout_3.addWidget(self.previewPlot)
        self.settingsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.settingsHorizontalLayout.setObjectName("settingsHorizontalLayout")
        self.itemVerticalLayout = QtWidgets.QVBoxLayout()
        self.itemVerticalLayout.setObjectName("itemVerticalLayout")
        self.itemListLabel = QtWidgets.QLabel(previewPlotFrame)
        self.itemListLabel.setObjectName("itemListLabel")
        self.itemVerticalLayout.addWidget(self.itemListLabel)
        self.itemListWidget = QtWidgets.QListWidget(previewPlotFrame)
        self.itemListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.itemListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.itemListWidget.setSelectionRectVisible(True)
        self.itemListWidget.setObjectName("itemListWidget")
        self.itemVerticalLayout.addWidget(self.itemListWidget)
        self.settingsHorizontalLayout.addLayout(self.itemVerticalLayout)
        self.scrollArea = QtWidgets.QScrollArea(previewPlotFrame)
        self.scrollArea.setMinimumSize(QtCore.QSize(216, 0))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.settingsVerticalLayout = QtWidgets.QWidget()
        self.settingsVerticalLayout.setGeometry(QtCore.QRect(0, 0, 538, 216))
        self.settingsVerticalLayout.setObjectName("settingsVerticalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsVerticalLayout)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultGridLayout = QtWidgets.QGridLayout()
        self.defaultGridLayout.setObjectName("defaultGridLayout")
        self.axesComboBox = QtWidgets.QComboBox(self.settingsVerticalLayout)
        self.axesComboBox.setObjectName("axesComboBox")
        self.axesComboBox.addItem("")
        self.axesComboBox.addItem("")
        self.axesComboBox.addItem("")
        self.defaultGridLayout.addWidget(self.axesComboBox, 0, 1, 1, 1)
        self.formatLabel = QtWidgets.QLabel(self.settingsVerticalLayout)
        self.formatLabel.setObjectName("formatLabel")
        self.defaultGridLayout.addWidget(self.formatLabel, 1, 0, 1, 1)
        self.formatComboBox = QtWidgets.QComboBox(self.settingsVerticalLayout)
        self.formatComboBox.setObjectName("formatComboBox")
        self.formatComboBox.addItem("")
        self.formatComboBox.addItem("")
        self.formatComboBox.addItem("")
        self.formatComboBox.addItem("")
        self.defaultGridLayout.addWidget(self.formatComboBox, 1, 1, 1, 1)
        self.axesLabel = QtWidgets.QLabel(self.settingsVerticalLayout)
        self.axesLabel.setObjectName("axesLabel")
        self.defaultGridLayout.addWidget(self.axesLabel, 0, 0, 1, 1)
        self.defaultGridLayout.setColumnStretch(0, 1)
        self.defaultGridLayout.setColumnStretch(1, 4)
        self.verticalLayout.addLayout(self.defaultGridLayout)
        self.customGridLayout = QtWidgets.QGridLayout()
        self.customGridLayout.setContentsMargins(-1, -1, -1, 0)
        self.customGridLayout.setObjectName("customGridLayout")
        self.verticalLayout.addLayout(self.customGridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.settingsVerticalLayout)
        self.settingsHorizontalLayout.addWidget(self.scrollArea)
        self.settingsHorizontalLayout.setStretch(0, 1)
        self.settingsHorizontalLayout.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.settingsHorizontalLayout)
        self.itemListLabel.setBuddy(self.itemListWidget)
        self.formatLabel.setBuddy(self.formatComboBox)
        self.axesLabel.setBuddy(self.axesComboBox)

        self.retranslateUi(previewPlotFrame)
        self.formatComboBox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(previewPlotFrame)
        previewPlotFrame.setTabOrder(self.itemListWidget, self.scrollArea)
        previewPlotFrame.setTabOrder(self.scrollArea, self.axesComboBox)
        previewPlotFrame.setTabOrder(self.axesComboBox, self.formatComboBox)

    def retranslateUi(self, previewPlotFrame):
        previewPlotFrame.setWindowTitle(QtWidgets.QApplication.translate("previewPlotFrame", "Frame", None, -1))
        self.itemListLabel.setText(QtWidgets.QApplication.translate("previewPlotFrame", "Items:", None, -1))
        self.axesComboBox.setItemText(0, QtWidgets.QApplication.translate("previewPlotFrame", "Rectangular", None, -1))
        self.axesComboBox.setItemText(1, QtWidgets.QApplication.translate("previewPlotFrame", "Polar", None, -1))
        self.axesComboBox.setItemText(2, QtWidgets.QApplication.translate("previewPlotFrame", "Smith", None, -1))
        self.formatLabel.setText(QtWidgets.QApplication.translate("previewPlotFrame", "Format:", None, -1))
        self.formatComboBox.setItemText(0, QtWidgets.QApplication.translate("previewPlotFrame", "Re", None, -1))
        self.formatComboBox.setItemText(1, QtWidgets.QApplication.translate("previewPlotFrame", "Re_Im", None, -1))
        self.formatComboBox.setItemText(2, QtWidgets.QApplication.translate("previewPlotFrame", "Lin_Deg", None, -1))
        self.formatComboBox.setItemText(3, QtWidgets.QApplication.translate("previewPlotFrame", "Log_Deg", None, -1))
        self.axesLabel.setText(QtWidgets.QApplication.translate("previewPlotFrame", "Axes:", None, -1))

from sknrf.app.dataviewer.view.figure import ContentFigure