# https://packaging.python.org/tutorials/packaging-projects/
[build-system]
requires = [
    "setuptools>=56",
    "wheel"
]

build-backend = "setuptools.build_meta"

# https://numpy.org/devdocs/reference/typing.html
[mypy]
plugins = "numpy.typing.mypy_plugin"
