from pydantic import BaseModel


class TsTick(BaseModel):
    ts_code = ''
    name = ''
    trade_time = ''
    pre_price = ''
    price = ''
    open = ''
    high = ''
    low = ''
    close = ''
    open_int = ''
    vol = ''
    amount = ''
    num = ''
    ask_price1 = ''
    ask_volume1 = ''
    bid_price1 = ''
    bid_volume1 = ''
    ask_price2 = ''
    ask_volume2 = ''
    bid_price2 = ''
    bid_volume2 = ''
    ask_price3 = ''
    ask_volume3 = ''
    bid_price3 = ''
    bid_volume3 = ''
    ask_price4 = ''
    ask_volume4 = ''
    bid_price4 = ''
    bid_volume4 = ''
    ask_price5 = ''
    ask_volume5 = ''
    bid_price5 = ''
    bid_volume5 = ''
    ask_price6 = ''
    ask_volume6 = ''
    bid_price6 = ''
    bid_volume6 = ''
    ask_price7 = ''
    ask_volume7 = ''
    bid_price7 = ''
    bid_volume7 = ''
    ask_price8 = ''
    ask_volume8 = ''
    bid_price8 = ''
    bid_volume8 = ''
    ask_price9 = ''
    ask_volume9 = ''
    bid_price9 = ''
    bid_volume9 = ''
    ask_price10 = ''
    ask_volume10 = ''
    bid_price10 = ''
    bid_volume10 = ''


class TsTickIdx(BaseModel):
    ts_code = ''
    name = ''
    trade_time = ''
    price = ''
    pre_price = ''
    open = ''
    high = ''
    low = ''
    vol = ''
    amount = ''


class TsTickOpt(BaseModel):
    ts_code = ''
    instrument_id = ''
    trade_time = ''
    pre_price = ''
    price = ''
    open = ''
    high = ''
    low = ''
    close = ''
    open_int = ''
    vol = ''
    amount = ''
    num = ''
    ask_price1 = ''
    ask_volume1 = ''
    bid_price1 = ''
    bid_volume1 = ''
    pre_delta = ''
    curr_delta = ''
    dif_price1 = ''
    dif_price2 = ''
    high_limit_price = ''
    low_limit_price = ''
    refer_price = ''


class TsTickFuture(BaseModel):
    ts_code = ''
    instrument_id = ''
    trade_time = ''
    pre_price = ''
    price = ''
    open = ''
    high = ''
    low = ''
    close = ''
    open_int = ''
    vol = ''
    amount = ''
    num = ''
    ask_price1 = ''
    ask_volume1 = ''
    bid_price1 = ''
    bid_volume1 = ''
    pre_delta = ''
    curr_delta = ''
    dif_price1 = ''
    dif_price2 = ''
    high_limit_price = ''
    low_limit_price = ''
    refer_price = ''
    pre_settle_price = ''
    settle_price = ''
