# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yggdrasil_decision_forests/model/abstract_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yggdrasil_decision_forests.dataset import data_spec_pb2 as yggdrasil__decision__forests_dot_dataset_dot_data__spec__pb2
from yggdrasil_decision_forests.dataset import weight_pb2 as yggdrasil__decision__forests_dot_dataset_dot_weight__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yggdrasil_decision_forests/model/abstract_model.proto',
  package='yggdrasil_decision_forests.model.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n5yggdrasil_decision_forests/model/abstract_model.proto\x12&yggdrasil_decision_forests.model.proto\x1a\x32yggdrasil_decision_forests/dataset/data_spec.proto\x1a/yggdrasil_decision_forests/dataset/weight.proto\"\xbf\x04\n\rAbstractModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x04task\x18\x02 \x01(\x0e\x32,.yggdrasil_decision_forests.model.proto.Task\x12\x15\n\rlabel_col_idx\x18\x03 \x01(\x05\x12Q\n\x07weights\x18\x04 \x01(\x0b\x32@.yggdrasil_decision_forests.dataset.proto.LinkedWeightDefinition\x12\x16\n\x0einput_features\x18\x05 \x03(\x05\x12!\n\x15ranking_group_col_idx\x18\x06 \x01(\x05:\x02-1\x12\x83\x01\n precomputed_variable_importances\x18\x07 \x03(\x0b\x32Y.yggdrasil_decision_forests.model.proto.AbstractModel.PrecomputedVariableImportancesEntry\x12\x32\n$classification_outputs_probabilities\x18\x08 \x01(\x08:\x04true\x1a\x84\x01\n#PrecomputedVariableImportancesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12L\n\x05value\x18\x02 \x01(\x0b\x32=.yggdrasil_decision_forests.model.proto.VariableImportanceSet:\x02\x38\x01\"?\n\x12VariableImportance\x12\x15\n\rattribute_idx\x18\x01 \x01(\x05\x12\x12\n\nimportance\x18\x02 \x01(\x01\"q\n\x15VariableImportanceSet\x12X\n\x14variable_importances\x18\x01 \x03(\x0b\x32:.yggdrasil_decision_forests.model.proto.VariableImportance*F\n\x04Task\x12\r\n\tUNDEFINED\x10\x00\x12\x12\n\x0e\x43LASSIFICATION\x10\x01\x12\x0e\n\nREGRESSION\x10\x02\x12\x0b\n\x07RANKING\x10\x03')
  ,
  dependencies=[yggdrasil__decision__forests_dot_dataset_dot_data__spec__pb2.DESCRIPTOR,yggdrasil__decision__forests_dot_dataset_dot_weight__pb2.DESCRIPTOR,])

_TASK = _descriptor.EnumDescriptor(
  name='Task',
  full_name='yggdrasil_decision_forests.model.proto.Task',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLASSIFICATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGRESSION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANKING', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=956,
  serialized_end=1026,
)
_sym_db.RegisterEnumDescriptor(_TASK)

Task = enum_type_wrapper.EnumTypeWrapper(_TASK)
UNDEFINED = 0
CLASSIFICATION = 1
REGRESSION = 2
RANKING = 3



_ABSTRACTMODEL_PRECOMPUTEDVARIABLEIMPORTANCESENTRY = _descriptor.Descriptor(
  name='PrecomputedVariableImportancesEntry',
  full_name='yggdrasil_decision_forests.model.proto.AbstractModel.PrecomputedVariableImportancesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.PrecomputedVariableImportancesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.PrecomputedVariableImportancesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=774,
)

_ABSTRACTMODEL = _descriptor.Descriptor(
  name='AbstractModel',
  full_name='yggdrasil_decision_forests.model.proto.AbstractModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.task', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_col_idx', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.label_col_idx', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.weights', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_features', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.input_features', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ranking_group_col_idx', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.ranking_group_col_idx', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='precomputed_variable_importances', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.precomputed_variable_importances', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classification_outputs_probabilities', full_name='yggdrasil_decision_forests.model.proto.AbstractModel.classification_outputs_probabilities', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ABSTRACTMODEL_PRECOMPUTEDVARIABLEIMPORTANCESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=774,
)


_VARIABLEIMPORTANCE = _descriptor.Descriptor(
  name='VariableImportance',
  full_name='yggdrasil_decision_forests.model.proto.VariableImportance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute_idx', full_name='yggdrasil_decision_forests.model.proto.VariableImportance.attribute_idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='importance', full_name='yggdrasil_decision_forests.model.proto.VariableImportance.importance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=839,
)


_VARIABLEIMPORTANCESET = _descriptor.Descriptor(
  name='VariableImportanceSet',
  full_name='yggdrasil_decision_forests.model.proto.VariableImportanceSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable_importances', full_name='yggdrasil_decision_forests.model.proto.VariableImportanceSet.variable_importances', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=841,
  serialized_end=954,
)

_ABSTRACTMODEL_PRECOMPUTEDVARIABLEIMPORTANCESENTRY.fields_by_name['value'].message_type = _VARIABLEIMPORTANCESET
_ABSTRACTMODEL_PRECOMPUTEDVARIABLEIMPORTANCESENTRY.containing_type = _ABSTRACTMODEL
_ABSTRACTMODEL.fields_by_name['task'].enum_type = _TASK
_ABSTRACTMODEL.fields_by_name['weights'].message_type = yggdrasil__decision__forests_dot_dataset_dot_weight__pb2._LINKEDWEIGHTDEFINITION
_ABSTRACTMODEL.fields_by_name['precomputed_variable_importances'].message_type = _ABSTRACTMODEL_PRECOMPUTEDVARIABLEIMPORTANCESENTRY
_VARIABLEIMPORTANCESET.fields_by_name['variable_importances'].message_type = _VARIABLEIMPORTANCE
DESCRIPTOR.message_types_by_name['AbstractModel'] = _ABSTRACTMODEL
DESCRIPTOR.message_types_by_name['VariableImportance'] = _VARIABLEIMPORTANCE
DESCRIPTOR.message_types_by_name['VariableImportanceSet'] = _VARIABLEIMPORTANCESET
DESCRIPTOR.enum_types_by_name['Task'] = _TASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AbstractModel = _reflection.GeneratedProtocolMessageType('AbstractModel', (_message.Message,), {

  'PrecomputedVariableImportancesEntry' : _reflection.GeneratedProtocolMessageType('PrecomputedVariableImportancesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ABSTRACTMODEL_PRECOMPUTEDVARIABLEIMPORTANCESENTRY,
    '__module__' : 'yggdrasil_decision_forests.model.abstract_model_pb2'
    # @@protoc_insertion_point(class_scope:yggdrasil_decision_forests.model.proto.AbstractModel.PrecomputedVariableImportancesEntry)
    })
  ,
  'DESCRIPTOR' : _ABSTRACTMODEL,
  '__module__' : 'yggdrasil_decision_forests.model.abstract_model_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil_decision_forests.model.proto.AbstractModel)
  })
_sym_db.RegisterMessage(AbstractModel)
_sym_db.RegisterMessage(AbstractModel.PrecomputedVariableImportancesEntry)

VariableImportance = _reflection.GeneratedProtocolMessageType('VariableImportance', (_message.Message,), {
  'DESCRIPTOR' : _VARIABLEIMPORTANCE,
  '__module__' : 'yggdrasil_decision_forests.model.abstract_model_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil_decision_forests.model.proto.VariableImportance)
  })
_sym_db.RegisterMessage(VariableImportance)

VariableImportanceSet = _reflection.GeneratedProtocolMessageType('VariableImportanceSet', (_message.Message,), {
  'DESCRIPTOR' : _VARIABLEIMPORTANCESET,
  '__module__' : 'yggdrasil_decision_forests.model.abstract_model_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil_decision_forests.model.proto.VariableImportanceSet)
  })
_sym_db.RegisterMessage(VariableImportanceSet)


_ABSTRACTMODEL_PRECOMPUTEDVARIABLEIMPORTANCESENTRY._options = None
# @@protoc_insertion_point(module_scope)
