# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 1.21.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CohortDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'period_definitions': 'list[PeriodDefinition]',
        'organization_id': 'str',
        'organization': 'Organization',
        'filters': 'list[CohortFilter]',
        'cohort_set_id': 'str',
        'cohort_set': 'CohortSet',
        'cohort_count_query_id': 'str',
        'cohort_list_query_id': 'str',
        'created_at': 'datetime',
        'created_by': 'str',
        'updated_at': 'datetime',
        'last_updated_by': 'str',
        'version': 'float'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'period_definitions': 'periodDefinitions',
        'organization_id': 'organizationId',
        'organization': 'organization',
        'filters': 'filters',
        'cohort_set_id': 'cohortSetId',
        'cohort_set': 'cohortSet',
        'cohort_count_query_id': 'cohortCountQueryId',
        'cohort_list_query_id': 'cohortListQueryId',
        'created_at': 'createdAt',
        'created_by': 'createdBy',
        'updated_at': 'updatedAt',
        'last_updated_by': 'lastUpdatedBy',
        'version': 'version'
    }

    def __init__(self, id=None, name=None, period_definitions=None, organization_id=None, organization=None, filters=None, cohort_set_id=None, cohort_set=None, cohort_count_query_id=None, cohort_list_query_id=None, created_at=None, created_by=None, updated_at=None, last_updated_by=None, version=None):  # noqa: E501
        """CohortDefinition - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._period_definitions = None
        self._organization_id = None
        self._organization = None
        self._filters = None
        self._cohort_set_id = None
        self._cohort_set = None
        self._cohort_count_query_id = None
        self._cohort_list_query_id = None
        self._created_at = None
        self._created_by = None
        self._updated_at = None
        self._last_updated_by = None
        self._version = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        self.period_definitions = period_definitions
        self.organization_id = organization_id
        if organization is not None:
            self.organization = organization
        self.filters = filters
        if cohort_set_id is not None:
            self.cohort_set_id = cohort_set_id
        if cohort_set is not None:
            self.cohort_set = cohort_set
        if cohort_count_query_id is not None:
            self.cohort_count_query_id = cohort_count_query_id
        if cohort_list_query_id is not None:
            self.cohort_list_query_id = cohort_list_query_id
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        if updated_at is not None:
            self.updated_at = updated_at
        if last_updated_by is not None:
            self.last_updated_by = last_updated_by
        if version is not None:
            self.version = version

    @property
    def id(self):
        """Gets the id of this CohortDefinition.  # noqa: E501


        :return: The id of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CohortDefinition.


        :param id: The id of this CohortDefinition.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CohortDefinition.  # noqa: E501


        :return: The name of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CohortDefinition.


        :param name: The name of this CohortDefinition.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def period_definitions(self):
        """Gets the period_definitions of this CohortDefinition.  # noqa: E501


        :return: The period_definitions of this CohortDefinition.  # noqa: E501
        :rtype: list[PeriodDefinition]
        """
        return self._period_definitions

    @period_definitions.setter
    def period_definitions(self, period_definitions):
        """Sets the period_definitions of this CohortDefinition.


        :param period_definitions: The period_definitions of this CohortDefinition.  # noqa: E501
        :type: list[PeriodDefinition]
        """
        if period_definitions is None:
            raise ValueError("Invalid value for `period_definitions`, must not be `None`")  # noqa: E501

        self._period_definitions = period_definitions

    @property
    def organization_id(self):
        """Gets the organization_id of this CohortDefinition.  # noqa: E501


        :return: The organization_id of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this CohortDefinition.


        :param organization_id: The organization_id of this CohortDefinition.  # noqa: E501
        :type: str
        """
        if organization_id is None:
            raise ValueError("Invalid value for `organization_id`, must not be `None`")  # noqa: E501

        self._organization_id = organization_id

    @property
    def organization(self):
        """Gets the organization of this CohortDefinition.  # noqa: E501


        :return: The organization of this CohortDefinition.  # noqa: E501
        :rtype: Organization
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this CohortDefinition.


        :param organization: The organization of this CohortDefinition.  # noqa: E501
        :type: Organization
        """

        self._organization = organization

    @property
    def filters(self):
        """Gets the filters of this CohortDefinition.  # noqa: E501


        :return: The filters of this CohortDefinition.  # noqa: E501
        :rtype: list[CohortFilter]
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """Sets the filters of this CohortDefinition.


        :param filters: The filters of this CohortDefinition.  # noqa: E501
        :type: list[CohortFilter]
        """
        if filters is None:
            raise ValueError("Invalid value for `filters`, must not be `None`")  # noqa: E501

        self._filters = filters

    @property
    def cohort_set_id(self):
        """Gets the cohort_set_id of this CohortDefinition.  # noqa: E501


        :return: The cohort_set_id of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._cohort_set_id

    @cohort_set_id.setter
    def cohort_set_id(self, cohort_set_id):
        """Sets the cohort_set_id of this CohortDefinition.


        :param cohort_set_id: The cohort_set_id of this CohortDefinition.  # noqa: E501
        :type: str
        """

        self._cohort_set_id = cohort_set_id

    @property
    def cohort_set(self):
        """Gets the cohort_set of this CohortDefinition.  # noqa: E501


        :return: The cohort_set of this CohortDefinition.  # noqa: E501
        :rtype: CohortSet
        """
        return self._cohort_set

    @cohort_set.setter
    def cohort_set(self, cohort_set):
        """Sets the cohort_set of this CohortDefinition.


        :param cohort_set: The cohort_set of this CohortDefinition.  # noqa: E501
        :type: CohortSet
        """

        self._cohort_set = cohort_set

    @property
    def cohort_count_query_id(self):
        """Gets the cohort_count_query_id of this CohortDefinition.  # noqa: E501


        :return: The cohort_count_query_id of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._cohort_count_query_id

    @cohort_count_query_id.setter
    def cohort_count_query_id(self, cohort_count_query_id):
        """Sets the cohort_count_query_id of this CohortDefinition.


        :param cohort_count_query_id: The cohort_count_query_id of this CohortDefinition.  # noqa: E501
        :type: str
        """

        self._cohort_count_query_id = cohort_count_query_id

    @property
    def cohort_list_query_id(self):
        """Gets the cohort_list_query_id of this CohortDefinition.  # noqa: E501


        :return: The cohort_list_query_id of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._cohort_list_query_id

    @cohort_list_query_id.setter
    def cohort_list_query_id(self, cohort_list_query_id):
        """Sets the cohort_list_query_id of this CohortDefinition.


        :param cohort_list_query_id: The cohort_list_query_id of this CohortDefinition.  # noqa: E501
        :type: str
        """

        self._cohort_list_query_id = cohort_list_query_id

    @property
    def created_at(self):
        """Gets the created_at of this CohortDefinition.  # noqa: E501


        :return: The created_at of this CohortDefinition.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this CohortDefinition.


        :param created_at: The created_at of this CohortDefinition.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this CohortDefinition.  # noqa: E501


        :return: The created_by of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this CohortDefinition.


        :param created_by: The created_by of this CohortDefinition.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def updated_at(self):
        """Gets the updated_at of this CohortDefinition.  # noqa: E501


        :return: The updated_at of this CohortDefinition.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this CohortDefinition.


        :param updated_at: The updated_at of this CohortDefinition.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def last_updated_by(self):
        """Gets the last_updated_by of this CohortDefinition.  # noqa: E501


        :return: The last_updated_by of this CohortDefinition.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_by

    @last_updated_by.setter
    def last_updated_by(self, last_updated_by):
        """Sets the last_updated_by of this CohortDefinition.


        :param last_updated_by: The last_updated_by of this CohortDefinition.  # noqa: E501
        :type: str
        """

        self._last_updated_by = last_updated_by

    @property
    def version(self):
        """Gets the version of this CohortDefinition.  # noqa: E501


        :return: The version of this CohortDefinition.  # noqa: E501
        :rtype: float
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this CohortDefinition.


        :param version: The version of this CohortDefinition.  # noqa: E501
        :type: float
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CohortDefinition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CohortDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
