
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-09T09:30:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "598b0a009475369dcddc47db2d2fb4d91f199f40",
 "version": "0.13.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
