
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T11:16:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b8e3312f404016706ced59ba52f6c742ca483e1",
 "version": "0.7.1.post.dev146"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
