[tool.poetry]
name = "qeclab"
version = "0.3.1"
description = ""
authors = ["maxtremblay <m@xtremblay.ca>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
pandas = "^1.3.0"
multiprocess = "^0.70.12"
dill = "^0.3.4"
qecstruct = "^0.2.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
