image: "python:3.9"

before_script:
  - python --version
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements-dev.txt
  - pip install .

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint mrtoolstheme/*.py

