# Generated by Django 3.1.8 on 2021-05-14 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automations', '0005_automationmodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationmodel',
            name='key',
            field=models.CharField(default='', max_length=64, verbose_name='Eindeutiger Hash-Wert'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='interaction_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Zugewiesene Gruppe'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='interaction_permissions',
            field=models.JSONField(default=list, help_text='Liste von Permissions in der Form <code>app_label.codename</code>', verbose_name='Benötigte Permissions'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='interaction_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesener Nutzer'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='requires_interaction',
            field=models.BooleanField(default=False, verbose_name='Verlangt Interaktion'),
        ),
    ]
