[tool.poetry]
name = "d2b-sidecarless-nii"
version = "1.0.0"
description = "Plugin for the d2b package to handle NIfTI images without sidecars"
authors = ["Andrew Ross <andrew.ross.mail@gmail.com>"]

readme = "README.md"

keywords = ["neuroscience", "neuroimaging", "bids", "nifti", "nii"]

homepage = "https://github.com/d2b-dev/d2b-sidecarless-nii"
repository = "https://github.com/d2b-dev/d2b-sidecarless-nii"
documentation = "https://github.com/d2b-dev/d2b-sidecarless-nii"

classifiers = [
    "Environment :: Console",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
d2b = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
flake8 = "^4.0.1"
pylint = "^2.11.1"
reorder-python-imports = "^2.6.0"
pre-commit = "^2.15.0"
bump2version = "^1.0.1"
pytest = "^6.2.5"

[tool.poetry.plugins.d2b]
"sidecarless_nii" = "d2b_sidecarless_nii"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
