
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-07T02:20:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "19a5473acc496d2aa67de4625b9ce0e61ae34dfa",
 "version": "0.3.dev2145"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
