[tool.poetry]
name = "brain_games_by_ms"
version = "0.1.0"
description = "Brain-games, project on hexlet"
authors = ["Mikhail Smotrin <iseeuqq@gmail.com>"]
repository = "https://github.com/mickysmt/python-project-lvl1"
packages = [
  { include = "brain_games" },
]
classifiers = [
    "Topic :: Education"
]

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.4"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
brain-even = "brain_games.scripts.brain_even:main"
brain-calc = "brain_games.scripts.brain_calc:main"
brain-gcd = "brain_games.scripts.brain_gcd:main"
brain-progression = "brain_games.scripts.brain_progression:main"
brain-is-prime = "brain_games.scripts.brain_is_prime:main"