VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('08')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('14')
MAJOR_VERSION = 1
MINOR_VERSION = 4
PATCH_VERSION = 202111081214
version_date = '2021/11/08 12:14'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
