stages:
  - pre-commit
  - test-suite

pre-commit:
  stage: pre-commit
  image: python:3.8-slim-buster
  before_script:
    - apt-get update && apt-get install -y git
    - python -m pip install --upgrade pip
    - pip install pre-commit
    - pre-commit install --install-hooks
    - chmod -R g-w,o-w . && umask 0022
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files

.test-suite:
  stage: test-suite
  needs:
    - pre-commit
  before_script:
    - apt-get update
    - apt-get install -y git
    # Pyinstaller system requirements
    - apt-get install -y binutils libc-bin
    # For codecoverage uploads
    - apt-get install -y curl gpg
    # For libvirt tests
    - apt-get install -y gcc pkg-config libvirt-dev
    - python3 -m pip install nox
  script:
    - export TIAMAT_PIP_DEBUG=1
    - nox -e tests-3 -- -vv
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit: artifacts/junit-report.xml
    expire_in: 30 days
  after_script:
    - set -ex
    - cicd/upload-code-coverage.sh

tests-3.6:
  extends: .test-suite
  image: python:3.6-slim-buster

tests-3.7:
  extends: .test-suite
  image: python:3.7-slim-buster

tests-3.8:
  extends: .test-suite
  image: python:3.8-slim-buster

tests-3.9:
  extends: .test-suite
  image: python:3.9-slim-buster

#tests-3.10:
#  extends: .test-suite
#  image: python:3.10-slim-buster
