# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QSequencerView.ui',
# licensing of 'QSequencerView.ui' applies.
#
# Created: Mon Jan 14 10:58:44 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_sequencerMenu(object):
    def setupUi(self, sequencerMenu):
        sequencerMenu.setObjectName("sequencerMenu")
        sequencerMenu.resize(1388, 759)
        self.centralwidget = QtWidgets.QWidget(sequencerMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        sequencerMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1388, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBuild = QtWidgets.QMenu(self.menubar)
        self.menuBuild.setObjectName("menuBuild")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        sequencerMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sequencerMenu)
        self.statusbar.setObjectName("statusbar")
        sequencerMenu.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(sequencerMenu)
        self.toolBar.setEnabled(True)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        sequencerMenu.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionHelp = QtWidgets.QAction(sequencerMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/question_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")
        self.actionLoad = QtWidgets.QAction(sequencerMenu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon1)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(sequencerMenu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG/black/32/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(sequencerMenu)
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(sequencerMenu)
        self.actionClose.setObjectName("actionClose")
        self.actionNew = QtWidgets.QAction(sequencerMenu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG/black/32/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName("actionNew")
        self.actionStep = QtWidgets.QAction(sequencerMenu)
        self.actionStep.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/PNG/green/32/circled_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStep.setIcon(icon4)
        self.actionStep.setObjectName("actionStep")
        self.actionStop = QtWidgets.QAction(sequencerMenu)
        self.actionStop.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/PNG/red/32/circled_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStop.setIcon(icon5)
        self.actionStop.setObjectName("actionStop")
        self.actionRun = QtWidgets.QAction(sequencerMenu)
        self.actionRun.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_border_triangle_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/PNG/green/32/circled_border_triangle_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRun.setIcon(icon6)
        self.actionRun.setObjectName("actionRun")
        self.actionCode = QtWidgets.QAction(sequencerMenu)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCode.setIcon(icon7)
        self.actionCode.setObjectName("actionCode")
        self.actionCompile = QtWidgets.QAction(sequencerMenu)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/PNG/black/32/wrench.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompile.setIcon(icon8)
        self.actionCompile.setObjectName("actionCompile")
        self.menuHelp.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuBuild.addAction(self.actionCode)
        self.menuBuild.addAction(self.actionCompile)
        self.menuDebug.addAction(self.actionStep)
        self.menuDebug.addAction(self.actionRun)
        self.menuDebug.addAction(self.actionStop)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBuild.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCode)
        self.toolBar.addAction(self.actionCompile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStep)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStop)

        self.retranslateUi(sequencerMenu)
        QtCore.QMetaObject.connectSlotsByName(sequencerMenu)

    def retranslateUi(self, sequencerMenu):
        sequencerMenu.setWindowTitle(QtWidgets.QApplication.translate("sequencerMenu", "Sequencer Menu", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("sequencerMenu", "Help", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("sequencerMenu", "File", None, -1))
        self.menuBuild.setTitle(QtWidgets.QApplication.translate("sequencerMenu", "Build", None, -1))
        self.menuDebug.setTitle(QtWidgets.QApplication.translate("sequencerMenu", "Debug", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("sequencerMenu", "toolBar", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("sequencerMenu", "Help", None, -1))
        self.actionHelp.setToolTip(QtWidgets.QApplication.translate("sequencerMenu", "Help", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("sequencerMenu", "Load", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("sequencerMenu", "Save", None, -1))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("sequencerMenu", "Save As", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("sequencerMenu", "Close", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("sequencerMenu", "New", None, -1))
        self.actionStep.setText(QtWidgets.QApplication.translate("sequencerMenu", "Step", None, -1))
        self.actionStep.setToolTip(QtWidgets.QApplication.translate("sequencerMenu", "Step", None, -1))
        self.actionStop.setText(QtWidgets.QApplication.translate("sequencerMenu", "Stop", None, -1))
        self.actionStop.setToolTip(QtWidgets.QApplication.translate("sequencerMenu", "Stop", None, -1))
        self.actionRun.setText(QtWidgets.QApplication.translate("sequencerMenu", "Run", None, -1))
        self.actionRun.setToolTip(QtWidgets.QApplication.translate("sequencerMenu", "Run", None, -1))
        self.actionCode.setText(QtWidgets.QApplication.translate("sequencerMenu", "Code", None, -1))
        self.actionCompile.setText(QtWidgets.QApplication.translate("sequencerMenu", "Compile", None, -1))
        self.actionCompile.setToolTip(QtWidgets.QApplication.translate("sequencerMenu", "Compile C Binary", None, -1))

