
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-04T20:26:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cb157f38f11e881e5fc7f07371d3fde6467aab7",
 "version": "1.0.1.post.dev51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
