[tool.poetry]
name = "us2anonymize"
version = "0.1.0"
description = ""
authors = ["mathias <mathias@us2.ai>"]

[tool.poetry.dependencies]
python = ">=3.7.5,<3.11"
opencv-python = "<4.5.4"
numpy = "^1.21.3"
pydicom = "^2.2.2"
watchdog = "^2.1.6"
python-gdcm = "^3.0.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
anonymize = "us2anonymize.anonymize:main"