[tool.poetry]
name = "mlflow-iap-token"
version = "0.1.0"
description = ""
authors = ["Myung Kim <agilemlops@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# [tool.poetry.plugins] # Optional super table

[tool.poetry.plugins."mlflow.request_header_provider"]
unused = "mlflow_iap_token.iap_token:IdentityAwareProxyPluginRequestHeaderProvider"
