
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T13:14:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2558d40e7cc1ad83664954294fb497ec38d3331",
 "version": "4.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
