
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T13:37:48-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d06b7aed6e4daaacf7927cefe9755d40f088f84",
 "version": "2.8.6.post0.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
