[tool.poetry]
name = "dictbelt"
version = "1.0.2"
description = "A batbelt utility for dictionaries"
authors = ["Steeleye <python.devs@steel-eye.com>"]
license = "MIT"
readme = "README.md"
keywords = ["dict", "walk", "traverse"]
homepage = "https://github.com/Etenil/dictbelt"

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

