[tool.poetry]
name = "thirdweb-sdk"
version = "0.2.1"
description = "Official ThirdWeb sdk"
authors = ["Ibrahim Ahmed <abe@thirdweb.com>", "Jake Loo <jake@thirdweb.com>", "Ayush Pathak <ayush@thirdweb.com>"]
packages = [
    { include = "nftlabs/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.6"
web3 = "^5.24.0"
0x-contract-wrappers = "^2.0.0"
dataclasses-json = "^0.5.6"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
