[tool.poetry]
name = "hcube"
version = "0.1.3"
description = "HCube is a simple ORM for working with hyper-cube OLAP data stored in various backends."
authors = ["Beda Kosata <beda@bigdigdata.com>"]
license = "WTFPL"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8.10"
clickhouse-driver = "^0.2.2"
python-decouple = "^3.5"
psycopg2-binary = "^2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.9b0"
pre-commit = "^2.15.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py38"]
