
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-08T13:26:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2ab8549c46927db3d8e0edb34de1091cff07a22",
 "version": "0.0.65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
