# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 590)
        MainWindow.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_contacts = QtWidgets.QLabel(self.centralwidget)
        self.label_contacts.setGeometry(QtCore.QRect(80, 10, 151, 16))
        self.label_contacts.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(63, 0, 189);")
        self.label_contacts.setObjectName("label_contacts")
        self.list_contacts = QtWidgets.QListView(self.centralwidget)
        self.list_contacts.setGeometry(QtCore.QRect(10, 30, 291, 441))
        self.list_contacts.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.list_contacts.setObjectName("list_contacts")
        self.label_message_history = QtWidgets.QLabel(self.centralwidget)
        self.label_message_history.setGeometry(QtCore.QRect(450, 10, 181, 16))
        self.label_message_history.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(63, 0, 189);")
        self.label_message_history.setObjectName("label_message_history")
        self.list_message_history = QtWidgets.QListView(self.centralwidget)
        self.list_message_history.setGeometry(QtCore.QRect(360, 30, 341, 301))
        self.list_message_history.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.list_message_history.setObjectName("list_message_history")
        self.label_new_message = QtWidgets.QLabel(self.centralwidget)
        self.label_new_message.setGeometry(QtCore.QRect(420, 340, 231, 16))
        self.label_new_message.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(63, 0, 189);")
        self.label_new_message.setObjectName("label_new_message")
        self.list_new_message = QtWidgets.QListView(self.centralwidget)
        self.list_new_message.setGeometry(QtCore.QRect(360, 370, 341, 101))
        self.list_new_message.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.list_new_message.setObjectName("list_new_message")
        self.push_add_contact = QtWidgets.QPushButton(self.centralwidget)
        self.push_add_contact.setGeometry(QtCore.QRect(20, 490, 121, 28))
        self.push_add_contact.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(63, 0, 189);")
        self.push_add_contact.setObjectName("push_add_contact")
        self.push_delete_contact = QtWidgets.QPushButton(self.centralwidget)
        self.push_delete_contact.setGeometry(QtCore.QRect(170, 490, 121, 28))
        self.push_delete_contact.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(63, 0, 189);")
        self.push_delete_contact.setObjectName("push_delete_contact")
        self.push_clean_field = QtWidgets.QPushButton(self.centralwidget)
        self.push_clean_field.setGeometry(QtCore.QRect(380, 490, 121, 28))
        self.push_clean_field.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(63, 0, 189);")
        self.push_clean_field.setObjectName("push_clean_field")
        self.push_send_message = QtWidgets.QPushButton(self.centralwidget)
        self.push_send_message.setGeometry(QtCore.QRect(530, 490, 151, 28))
        self.push_send_message.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(63, 0, 189);")
        self.push_send_message.setObjectName("push_send_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_contacts = QtWidgets.QMenu(self.menubar)
        self.menu_contacts.setObjectName("menu_contacts")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_add_contact = QtWidgets.QAction(MainWindow)
        self.menu_add_contact.setObjectName("menu_add_contact")
        self.menu_exit = QtWidgets.QAction(MainWindow)
        self.menu_exit.setObjectName("menu_exit")
        self.menu_delete_contact = QtWidgets.QAction(MainWindow)
        self.menu_delete_contact.setObjectName("menu_delete_contact")
        self.menu_file.addAction(self.menu_exit)
        self.menu_contacts.addAction(self.menu_add_contact)
        self.menu_contacts.addAction(self.menu_delete_contact)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_contacts.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_contacts.setText(_translate("MainWindow", "Список контактов:"))
        self.label_message_history.setText(_translate("MainWindow", "История сообщений:"))
        self.label_new_message.setText(_translate("MainWindow", "Введите новое сообщение:"))
        self.push_add_contact.setText(_translate("MainWindow", "Добавить контакт"))
        self.push_delete_contact.setText(_translate("MainWindow", "Удалить контакт"))
        self.push_clean_field.setText(_translate("MainWindow", "Очистить поле"))
        self.push_send_message.setText(_translate("MainWindow", "Отправить сообщение"))
        self.menu_file.setTitle(_translate("MainWindow", "Файл"))
        self.menu_contacts.setTitle(_translate("MainWindow", "Контакты"))
        self.menu_add_contact.setText(_translate("MainWindow", "Добавить контакт"))
        self.menu_exit.setText(_translate("MainWindow", "Выход"))
        self.menu_delete_contact.setText(_translate("MainWindow", "Удалить контакт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
