[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 120
skip-numeric-underscore-normalization = true

[tool.tox]
legacy_tox_ini="""
[tox]
isolated_build = true
skip_install = true
envlist =
    py{36,37,38,39},
[testenv]
deps =
    coverage[toml]
commands =
    coverage run -a runtests.py
    coverage report
"""

[tool.coverage.run]
source = ["."]
branch = true
omit = ["./venv/*", "*tests*", "*apps.py", "*manage.py", "*__init__.py", "*migrations*", "*asgi*", "*wsgi*", "*urls.py", "*translation.py", "./.tox/*", "*.pyc", "setup.py"]


[tool.coverage.report]
ignore_errors = true
exclude_lines = ["raise NotImplementedError", "raise AssertionError", "if __name__ == .__main__.:", "pragma: no cover"]
omit = ["./venv/*", "*tests*", "*apps.py", "*manage.py", "*__init__.py", "*migrations*", "*asgi*", "*wsgi*", "*urls.py", "*translation.py", "./.tox/*", "*.pyc", "setup.py"]
skip_covered = true
skip_empty = true

[tool.coverage.html]
directory = "coverage_html_report"
show_contexts = true
