[tool.poetry]
name = "teselagen"
version = "0.4.3"
description = "Teselagen Biotechnology API client"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = "https://github.com/TeselaGen/api-client"
documentation = ""
keywords = [
    "Synthetic Biology",
    "Teselagen",
    "DBTL",
    "CRISPR",
    "DNA Assembly"
]

[tool.poetry.dependencies]
python = "^3.9.6"
setuptools = "^45.1.0"
pytest = "^5.4.3"
pytest-xdist = "^1.34.0"
pytest-cov = "^2.12.1"
pytest-notebook = "^0.6.1"
pytest-datadir = "^1.3.1"
requests = "^2.26.0"
requests-mock = "^1.9.3"
fastaparser = "^1.1"
pandas = "^1.1.5"
dna_features_viewer = "^3.0.3"
tqdm = "^4.61.2"
single_version = "^1.5.1"
SecretColors = "^1.2.4"
tenacity = "^8.0.0"
openpyxl = "^3.0.7"

[tool.poetry.dev-dependencies]
seaborn = "^0.11.1"
notebook = "^6.4.0"
mypy = "^0.812"
yapf = "^0.31.0"
nglview = "^3.0.3"
nbconvert="5.6.1" # Temporarily pinned for avoiding https://github.com/jupyter/jupyter_client/issues/637
jupyter-client = "6.1.12" # Temporarily pinned for avoiding https://github.com/jupyter/jupyter_client/issues/637


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
