
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-08T10:34:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b51b545f3aef0742a2d250c75cc998ba6c9e57b2",
 "version": "3.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
