[tool.poetry]
name = "viecpro_vis"
version = "0.1.1"
description = "Django-App providing visualisations for the APIS-VieCPro instance."
authors = ["Gregor Pirgie <gregor.pirgie@univie.ac.at>"]

[tool.poetry.dependencies]
python = ">=3.6, <3.9"
apis-core = "^0.16.37"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
