
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-08T16:06:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad7d0a21188ef5035f104131d12dcd959b0bc109",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
