[tool.towncrier]
    package="web3metis"
    filename = "docs/releases.rst"
    directory = "newsfragments"
    underlines = ["-", "~", "^"]
    issue_format = "`#{issue} <https://github.com/thimper/web3.py/issues/{issue}>`__"
    title_format = "v{version} ({project_date})"
