[tool.poetry]
name = "matchms-plotly"
version = "0.1.4"
description = "Plot Matchms spectra with Plotly]."
authors = ["Yann Beauxis <dev@yannbeauxis.net>"]
license = "Apache-2.0"
homepage = "https://gitlab.com/metwork/libs/matchms-plotly"
repository = "https://gitlab.com/metwork/libs/matchms-plotly"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.1"
matchms  = "^0.9.0"
pandas = "^1.2.1"
plotly = "^4.14.3"
numpy = "^1.20.0" # https://githubmemory.com/repo/pystatgen/sgkit/issues/631

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
pytest-cov = "^2.12.1"
jupyterlab = "^3.0.7"
rope = "^0.19.0"
black = "^21.5b1"
mypy = "^0.910"
flake8 = "^3.9.2"
types-setuptools = "^57.0.2"
pandas-stubs = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
