
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-07T13:44:50+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1be08c81b072f68ab0e2e541243d0cb85484f7f",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
