[tool.poetry]
name = "caspius"
version = "0.1.0"
description = "Simple log system for python"
authors = ["Dan Gost <t.me/dangost>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
