
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T15:25:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d1da0258866a6eb9f872415a73a9513794809a0",
 "version": "5.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
