"""blog

Revision ID: 5258a1777d2a
Revises: a3ffa1d8ccd5
Create Date: 2021-11-06 00:26:34.831835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5258a1777d2a"
down_revision = "a3ffa1d8ccd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("user", sa.CHAR(36), nullable=True),
        sa.ForeignKeyConstraint(
            ["user"], ["users.id"], name="fk_blogs_users_id_user"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blogs")
    # ### end Alembic commands ###
