
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-04T14:03:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e9a210db440b31d0da1d7b5c87bac96acfb6610",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
