
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T19:44:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "04bf9785e0c956d4a418b8150f6c0a5d7ba598c2",
 "version": "0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
