# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phenopackets/schema/v2/core/measurement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .  import base_pb2 as phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='phenopackets/schema/v2/core/measurement.proto',
  package='org.phenopackets.schema.v2.core',
  syntax='proto3',
  serialized_options=b'\n\037org.phenopackets.schema.v2.coreP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-phenopackets/schema/v2/core/measurement.proto\x12\x1forg.phenopackets.schema.v2.core\x1a&phenopackets/schema/v2/core/base.proto\"\xfb\x02\n\x0bMeasurement\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12=\n\x05\x61ssay\x18\x02 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12\x37\n\x05value\x18\x03 \x01(\x0b\x32&.org.phenopackets.schema.v2.core.ValueH\x00\x12\x46\n\rcomplex_value\x18\x04 \x01(\x0b\x32-.org.phenopackets.schema.v2.core.ComplexValueH\x00\x12\x43\n\rtime_observed\x18\x05 \x01(\x0b\x32,.org.phenopackets.schema.v2.core.TimeElement\x12=\n\tprocedure\x18\x06 \x01(\x0b\x32*.org.phenopackets.schema.v2.core.ProcedureB\x13\n\x11measurement_value\"\x99\x01\n\x05Value\x12=\n\x08quantity\x18\x01 \x01(\x0b\x32).org.phenopackets.schema.v2.core.QuantityH\x00\x12H\n\x0eontology_class\x18\x02 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClassH\x00\x42\x07\n\x05value\"X\n\x0c\x43omplexValue\x12H\n\x10typed_quantities\x18\x01 \x03(\x0b\x32..org.phenopackets.schema.v2.core.TypedQuantity\"\xa1\x01\n\x08Quantity\x12<\n\x04unit\x18\x01 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12\r\n\x05value\x18\x02 \x01(\x01\x12H\n\x0freference_range\x18\x03 \x01(\x0b\x32/.org.phenopackets.schema.v2.core.ReferenceRange\"\x8a\x01\n\rTypedQuantity\x12<\n\x04type\x18\x01 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12;\n\x08quantity\x18\x02 \x01(\x0b\x32).org.phenopackets.schema.v2.core.Quantity\"i\n\x0eReferenceRange\x12<\n\x04unit\x18\x01 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12\x0b\n\x03low\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x42#\n\x1forg.phenopackets.schema.v2.coreP\x01\x62\x06proto3'
  ,
  dependencies=[phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2.DESCRIPTOR,])




_MEASUREMENT = _descriptor.Descriptor(
  name='Measurement',
  full_name='org.phenopackets.schema.v2.core.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='org.phenopackets.schema.v2.core.Measurement.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assay', full_name='org.phenopackets.schema.v2.core.Measurement.assay', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.phenopackets.schema.v2.core.Measurement.value', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='complex_value', full_name='org.phenopackets.schema.v2.core.Measurement.complex_value', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_observed', full_name='org.phenopackets.schema.v2.core.Measurement.time_observed', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='procedure', full_name='org.phenopackets.schema.v2.core.Measurement.procedure', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='measurement_value', full_name='org.phenopackets.schema.v2.core.Measurement.measurement_value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=123,
  serialized_end=502,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='org.phenopackets.schema.v2.core.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity', full_name='org.phenopackets.schema.v2.core.Value.quantity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ontology_class', full_name='org.phenopackets.schema.v2.core.Value.ontology_class', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='org.phenopackets.schema.v2.core.Value.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=505,
  serialized_end=658,
)


_COMPLEXVALUE = _descriptor.Descriptor(
  name='ComplexValue',
  full_name='org.phenopackets.schema.v2.core.ComplexValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typed_quantities', full_name='org.phenopackets.schema.v2.core.ComplexValue.typed_quantities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=748,
)


_QUANTITY = _descriptor.Descriptor(
  name='Quantity',
  full_name='org.phenopackets.schema.v2.core.Quantity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit', full_name='org.phenopackets.schema.v2.core.Quantity.unit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.phenopackets.schema.v2.core.Quantity.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_range', full_name='org.phenopackets.schema.v2.core.Quantity.reference_range', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=751,
  serialized_end=912,
)


_TYPEDQUANTITY = _descriptor.Descriptor(
  name='TypedQuantity',
  full_name='org.phenopackets.schema.v2.core.TypedQuantity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='org.phenopackets.schema.v2.core.TypedQuantity.type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='org.phenopackets.schema.v2.core.TypedQuantity.quantity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=915,
  serialized_end=1053,
)


_REFERENCERANGE = _descriptor.Descriptor(
  name='ReferenceRange',
  full_name='org.phenopackets.schema.v2.core.ReferenceRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit', full_name='org.phenopackets.schema.v2.core.ReferenceRange.unit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='org.phenopackets.schema.v2.core.ReferenceRange.low', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='org.phenopackets.schema.v2.core.ReferenceRange.high', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1055,
  serialized_end=1160,
)

_MEASUREMENT.fields_by_name['assay'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_MEASUREMENT.fields_by_name['value'].message_type = _VALUE
_MEASUREMENT.fields_by_name['complex_value'].message_type = _COMPLEXVALUE
_MEASUREMENT.fields_by_name['time_observed'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._TIMEELEMENT
_MEASUREMENT.fields_by_name['procedure'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._PROCEDURE
_MEASUREMENT.oneofs_by_name['measurement_value'].fields.append(
  _MEASUREMENT.fields_by_name['value'])
_MEASUREMENT.fields_by_name['value'].containing_oneof = _MEASUREMENT.oneofs_by_name['measurement_value']
_MEASUREMENT.oneofs_by_name['measurement_value'].fields.append(
  _MEASUREMENT.fields_by_name['complex_value'])
_MEASUREMENT.fields_by_name['complex_value'].containing_oneof = _MEASUREMENT.oneofs_by_name['measurement_value']
_VALUE.fields_by_name['quantity'].message_type = _QUANTITY
_VALUE.fields_by_name['ontology_class'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['quantity'])
_VALUE.fields_by_name['quantity'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['ontology_class'])
_VALUE.fields_by_name['ontology_class'].containing_oneof = _VALUE.oneofs_by_name['value']
_COMPLEXVALUE.fields_by_name['typed_quantities'].message_type = _TYPEDQUANTITY
_QUANTITY.fields_by_name['unit'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_QUANTITY.fields_by_name['reference_range'].message_type = _REFERENCERANGE
_TYPEDQUANTITY.fields_by_name['type'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_TYPEDQUANTITY.fields_by_name['quantity'].message_type = _QUANTITY
_REFERENCERANGE.fields_by_name['unit'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
DESCRIPTOR.message_types_by_name['Measurement'] = _MEASUREMENT
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['ComplexValue'] = _COMPLEXVALUE
DESCRIPTOR.message_types_by_name['Quantity'] = _QUANTITY
DESCRIPTOR.message_types_by_name['TypedQuantity'] = _TYPEDQUANTITY
DESCRIPTOR.message_types_by_name['ReferenceRange'] = _REFERENCERANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENT,
  '__module__' : 'phenopackets.schema.v2.core.measurement_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.Measurement)
  })
_sym_db.RegisterMessage(Measurement)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'phenopackets.schema.v2.core.measurement_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.Value)
  })
_sym_db.RegisterMessage(Value)

ComplexValue = _reflection.GeneratedProtocolMessageType('ComplexValue', (_message.Message,), {
  'DESCRIPTOR' : _COMPLEXVALUE,
  '__module__' : 'phenopackets.schema.v2.core.measurement_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.ComplexValue)
  })
_sym_db.RegisterMessage(ComplexValue)

Quantity = _reflection.GeneratedProtocolMessageType('Quantity', (_message.Message,), {
  'DESCRIPTOR' : _QUANTITY,
  '__module__' : 'phenopackets.schema.v2.core.measurement_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.Quantity)
  })
_sym_db.RegisterMessage(Quantity)

TypedQuantity = _reflection.GeneratedProtocolMessageType('TypedQuantity', (_message.Message,), {
  'DESCRIPTOR' : _TYPEDQUANTITY,
  '__module__' : 'phenopackets.schema.v2.core.measurement_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.TypedQuantity)
  })
_sym_db.RegisterMessage(TypedQuantity)

ReferenceRange = _reflection.GeneratedProtocolMessageType('ReferenceRange', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCERANGE,
  '__module__' : 'phenopackets.schema.v2.core.measurement_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.ReferenceRange)
  })
_sym_db.RegisterMessage(ReferenceRange)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
