# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phenopackets/schema/v2/core/phenotypic_feature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .  import base_pb2 as phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='phenopackets/schema/v2/core/phenotypic_feature.proto',
  package='org.phenopackets.schema.v2.core',
  syntax='proto3',
  serialized_options=b'\n\037org.phenopackets.schema.v2.coreP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n4phenopackets/schema/v2/core/phenotypic_feature.proto\x12\x1forg.phenopackets.schema.v2.core\x1a&phenopackets/schema/v2/core/base.proto\"\xb9\x03\n\x11PhenotypicFeature\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12<\n\x04type\x18\x02 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12\x10\n\x08\x65xcluded\x18\x03 \x01(\x08\x12@\n\x08severity\x18\x04 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12\x41\n\tmodifiers\x18\x05 \x03(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12;\n\x05onset\x18\x06 \x01(\x0b\x32,.org.phenopackets.schema.v2.core.TimeElement\x12@\n\nresolution\x18\x07 \x01(\x0b\x32,.org.phenopackets.schema.v2.core.TimeElement\x12;\n\x08\x65vidence\x18\x08 \x03(\x0b\x32).org.phenopackets.schema.v2.core.EvidenceB#\n\x1forg.phenopackets.schema.v2.coreP\x01\x62\x06proto3'
  ,
  dependencies=[phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2.DESCRIPTOR,])




_PHENOTYPICFEATURE = _descriptor.Descriptor(
  name='PhenotypicFeature',
  full_name='org.phenopackets.schema.v2.core.PhenotypicFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='excluded', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.excluded', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.severity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modifiers', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.modifiers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onset', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.onset', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.resolution', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidence', full_name='org.phenopackets.schema.v2.core.PhenotypicFeature.evidence', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=571,
)

_PHENOTYPICFEATURE.fields_by_name['type'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_PHENOTYPICFEATURE.fields_by_name['severity'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_PHENOTYPICFEATURE.fields_by_name['modifiers'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_PHENOTYPICFEATURE.fields_by_name['onset'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._TIMEELEMENT
_PHENOTYPICFEATURE.fields_by_name['resolution'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._TIMEELEMENT
_PHENOTYPICFEATURE.fields_by_name['evidence'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._EVIDENCE
DESCRIPTOR.message_types_by_name['PhenotypicFeature'] = _PHENOTYPICFEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhenotypicFeature = _reflection.GeneratedProtocolMessageType('PhenotypicFeature', (_message.Message,), {
  'DESCRIPTOR' : _PHENOTYPICFEATURE,
  '__module__' : 'phenopackets.schema.v2.core.phenotypic_feature_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.PhenotypicFeature)
  })
_sym_db.RegisterMessage(PhenotypicFeature)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
