
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-09T17:49:49+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "b02eada798ff4c9007aa8ba60be8d2e6b3502da3",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
