parameters:
  featurestorebundle:
    db_name_template: '%kernel.environment%_feature_store'
    table_name_template: 'features_{entity}'
    base_path: 'dbfs:/user/hive/warehouse'
    latest_path_template: '%featurestorebundle.base_path%/%featurestorebundle.db_name_template%.db/%featurestorebundle.table_name_template%_latest'
    historized_path_template: '%featurestorebundle.base_path%/%featurestorebundle.db_name_template%.db/%featurestorebundle.table_name_template%_historized'
    archive_path_template: '%featurestorebundle.base_path%/archive/{entity}/{date}.delta'
    join_batch_size: 10
    writer: databricks
    metadata_api:
      enabled: False
      url:

services:
  featurestorebundle.logger:
    class: logging.Logger
    factory: ['@loggerbundle.LoggerFactory', 'create']
    arguments:
      - 'feature_store'

  featurestorebundle.db.TableNames:
    arguments:
      - '%featurestorebundle.db_name_template%'
      - '%featurestorebundle.table_name_template%'
      - '%featurestorebundle.latest_path_template%'
      - '%featurestorebundle.historized_path_template%'
      - '%featurestorebundle.archive_path_template%'

  featurestorebundle.delta.DeltaWriter:
    arguments:
      - '@featurestorebundle.logger'
    tags:
      - {name: 'feature.writer', alias: 'delta'}

  featurestorebundle.databricks.FeatureStoreWriter:
    arguments:
      - '@featurestorebundle.logger'
    tags:
      - {name: 'feature.writer', alias: 'databricks'}

  featurestorebundle.feature.EmptyTableCreator:

  featurestorebundle.feature.EmptyFileCreator:

  featurestorebundle.feature.EmptyDataFrameCreator:

  featurestorebundle.feature.FeatureDataMerger:
    arguments:
      - '%featurestorebundle.metadata_api.enabled%'
      - '@featurestorebundle.logger'

  featurestorebundle.feature.FeatureManager:
    arguments:
      - '@featurestorebundle.logger'

  featurestorebundle.feature.FeatureTemplateMatcher:

  featurestorebundle.feature.FeatureStore:

  featurestorebundle.metadata.MetadataWriter:
    arguments:
      - '@featurestorebundle.logger'

  featurestorebundle.metadata.MetadataHTMLDisplayer:

  featurestorebundle.metadata.TimeWindowHandler:

  featurestorebundle.feature.TablePreparer:

  featurestorebundle.feature.FeaturesPreparer:
    arguments:
      - '%featurestorebundle.join_batch_size%'

  featurestorebundle.gql.GraphQLTransport:
    class: gql.transport.requests.RequestsHTTPTransport
    arguments:
      url: '%featurestorebundle.metadata_api.url%'

  featurestorebundle.gql.GraphQLClient:
    class: gql.client.Client
    arguments:
      transport: '@featurestorebundle.gql.GraphQLTransport'
