
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-29T17:30:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ada1a067ad9b2c33b8ba2b2077db60417dc38fd",
 "version": "v11.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
