[tool.poetry]
name = "sp110e"
version = "0.3.0"
description = "Control SP110E BLE RGB LED device from computer"
authors = ["Pavel Roslovets <p.v.roslovets@gmail.com>"]
license = "MIT"
readme = "README.MD"
homepage = "https://github.com/roslovets/SP110E"
repository = "https://github.com/roslovets/SP110E"
keywords = ["SP110E", "RGB", "LED"]
classifiers =[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
    ]

[tool.poetry.dependencies]
python = ">=3.6"
bleak = "==0.13.0"
syncer = "==1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
