[package]
name = "cdshealpix"
version = "0.6.1"
authors = ["Matthieu Baumann <matthieu.baumann@astro.unistra.fr>", "F.-X. Pineau <francois-xavier.pineau@astro.unistra.fr>"]
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
categories = ["algorithms", "science"] 
repository = "https://github.com/cds-astro/cds-healpix-python"
description = "Python cdshealpix package wrapping code of the cdshealpix crate."
documentation = "https://cds-astro.github.io/cds-healpix-python"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "cdshealpix"
#path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
# The cdshealpix rust crate
#healpix = { package = "cdshealpix", git = 'https://github.com/cds-astro/cds-healpix-rust', branch = 'master' }
healpix = { package = "cdshealpix", version = "0.5.5" }
rayon = "1.5.1"

[dependencies.numpy]
version = "0.13.2"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[dependencies.ndarray]
version = "0.15.3"
default-features = false # do not include the default features, and optionally
                         # cherry-pick individual features
features = ["rayon"]

[package.metadata.maturin]
# Python dependencies needed by cdshealpix requires-dist = ["astropy~=4.2"]
requires-dist = ["astropy"]

