
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T15:09:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "357a0e7dc47e29536f7e1a2f8d48b6bb99b9f748",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
