# Generated by Django 2.2.11 on 2021-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_designer', '0003_auto_20211006_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternFieldRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок поле в связи')),
                ('pattern_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_designer.PatternField', verbose_name='Поле шаблона')),
                ('table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_designer.TableField', verbose_name='Поле таблицы')),
            ],
            options={
                'verbose_name': 'Связь поля шаблона',
                'verbose_name_plural': 'Связи полей шаблонов',
                'ordering': ('order',),
                'unique_together': {('order', 'pattern_field', 'table_field')},
            },
        ),
        migrations.AddField(
            model_name='patternfield',
            name='relations',
            field=models.ManyToManyField(blank=True, related_name='relations_pattern_fields', through='report_designer.PatternFieldRelation', to='report_designer.TableField', verbose_name='Связь с корневой таблицей'),
        ),
    ]
