# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QMainMenuView.ui',
# licensing of 'QMainMenuView.ui' applies.
#
# Created: Mon Jan 14 23:50:22 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.setEnabled(True)
        mainMenu.resize(1085, 806)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainMenu.sizePolicy().hasHeightForWidth())
        mainMenu.setSizePolicy(sizePolicy)
        mainMenu.setMinimumSize(QtCore.QSize(792, 117))
        mainMenu.setSizeIncrement(QtCore.QSize(0, 0))
        mainMenu.setFocusPolicy(QtCore.Qt.ClickFocus)
        mainMenu.setAutoFillBackground(False)
        mainMenu.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        mainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        mainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainMenu)
        self.statusbar.setObjectName("statusbar")
        mainMenu.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainMenu)
        self.toolBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.LeftToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        mainMenu.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtWidgets.QAction(mainMenu)
        self.actionLoad.setChecked(False)
        self.actionLoad.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon)
        self.actionLoad.setAutoRepeat(False)
        self.actionLoad.setVisible(True)
        self.actionLoad.setIconVisibleInMenu(True)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(mainMenu)
        self.actionSave.setCheckable(False)
        self.actionSave.setChecked(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(mainMenu)
        self.actionSave_As.setIcon(icon1)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAbout = QtWidgets.QAction(mainMenu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG/black/32/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(mainMenu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG/black/32/question_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon3)
        self.actionHelp.setObjectName("actionHelp")
        self.actionWebsite = QtWidgets.QAction(mainMenu)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionSingle = QtWidgets.QAction(mainMenu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_border_triangle_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/PNG/green/32/circled_border_triangle_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSingle.setIcon(icon4)
        self.actionSingle.setObjectName("actionSingle")
        self.actionSequencer = QtWidgets.QAction(mainMenu)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/PNG/green/32/circled_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSequencer.setIcon(icon5)
        self.actionSequencer.setObjectName("actionSequencer")
        self.actionPreferences = QtWidgets.QAction(mainMenu)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/PNG/black/32/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon6)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExit = QtWidgets.QAction(mainMenu)
        self.actionExit.setObjectName("actionExit")
        self.actionApp = QtWidgets.QAction(mainMenu)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/PNG/black/32/rocket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionApp.setIcon(icon7)
        self.actionApp.setObjectName("actionApp")
        self.actionSParameter = QtWidgets.QAction(mainMenu)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/PNG/green/32/circled_border_triangle_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSParameter.setIcon(icon8)
        self.actionSParameter.setObjectName("actionSParameter")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuRun.addAction(self.actionSParameter)
        self.menuRun.addAction(self.actionSingle)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionSequencer)
        self.menuRun.addAction(self.actionApp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSequencer)
        self.toolBar.addAction(self.actionApp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSParameter)
        self.toolBar.addAction(self.actionSingle)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        mainMenu.setWindowTitle(QtWidgets.QApplication.translate("mainMenu", "mainMenu", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("mainMenu", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("mainMenu", "Help", None, -1))
        self.menuRun.setTitle(QtWidgets.QApplication.translate("mainMenu", "Run", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("mainMenu", "toolBar", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("mainMenu", "Load...", None, -1))
        self.actionLoad.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "Load Previous Settings", None, -1))
        self.actionLoad.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+O", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("mainMenu", "Save", None, -1))
        self.actionSave.setToolTip(QtWidgets.QApplication.translate("mainMenu", "Save Settings", None, -1))
        self.actionSave.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "Save Current Settings", None, -1))
        self.actionSave.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+S", None, -1))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("mainMenu", "Save As...", None, -1))
        self.actionSave_As.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "Save Current Settings As...", None, -1))
        self.actionSave_As.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+Shift+S", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("mainMenu", "About", None, -1))
        self.actionAbout.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "About this Application", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("mainMenu", "Help", None, -1))
        self.actionHelp.setIconText(QtWidgets.QApplication.translate("mainMenu", "Help", None, -1))
        self.actionHelp.setToolTip(QtWidgets.QApplication.translate("mainMenu", "Help", None, -1))
        self.actionHelp.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "Browse Documentation Online", None, -1))
        self.actionWebsite.setText(QtWidgets.QApplication.translate("mainMenu", "Website", None, -1))
        self.actionWebsite.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "Visit Application Website Online", None, -1))
        self.actionSingle.setText(QtWidgets.QApplication.translate("mainMenu", "Single", None, -1))
        self.actionSingle.setToolTip(QtWidgets.QApplication.translate("mainMenu", "Single Measurement", None, -1))
        self.actionSingle.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+2", None, -1))
        self.actionSequencer.setText(QtWidgets.QApplication.translate("mainMenu", "Sequencer", None, -1))
        self.actionSequencer.setToolTip(QtWidgets.QApplication.translate("mainMenu", "Run Sequencer", None, -1))
        self.actionSequencer.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+3", None, -1))
        self.actionPreferences.setText(QtWidgets.QApplication.translate("mainMenu", "Preferences", None, -1))
        self.actionPreferences.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "Edit System Preferences", None, -1))
        self.actionPreferences.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+,", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("mainMenu", "Exit", None, -1))
        self.actionExit.setStatusTip(QtWidgets.QApplication.translate("mainMenu", "Exit the Application", None, -1))
        self.actionExit.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+Q", None, -1))
        self.actionApp.setText(QtWidgets.QApplication.translate("mainMenu", "App", None, -1))
        self.actionApp.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+A", None, -1))
        self.actionSParameter.setText(QtWidgets.QApplication.translate("mainMenu", "S-Parameter", None, -1))
        self.actionSParameter.setToolTip(QtWidgets.QApplication.translate("mainMenu", "S-Parameter Model", None, -1))
        self.actionSParameter.setShortcut(QtWidgets.QApplication.translate("mainMenu", "Ctrl+1", None, -1))

