# Generated by Django 2.2.11 on 2021-10-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_designer', '0006_auto_20211026_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfieldrelation',
            options={'ordering': ('-order',), 'verbose_name': 'Связь поля отчета', 'verbose_name_plural': 'Связи полей очтетов'},
        ),
        migrations.AlterField(
            model_name='reportfieldrelation',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('is_root', models.BooleanField(default=False, verbose_name='Основная таблица отчета')),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tables', to='report_designer.DBTable', verbose_name='Таблица БД')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tables', to='report_designer.Report', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Таблица отчета',
                'verbose_name_plural': 'Таблицы отчета',
                'ordering': ('order', '-pk'),
            },
        ),
    ]
