
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-04T17:24:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e7e66fb77e6a68acee854665f711a0178ddadbf",
 "version": "0.13.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
