[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "bws_jsonrpc"
dist-name = "bws-jsonrpc"
author = "Jose Angel Delgado"
author-email = "esojangel@gmail.com"
description-file = "README.md"
requires=[
    "jsonrpcserver",
    "flask"
]
requires-python=">=3.6"
classifiers=[
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.flit.sdist]
include = [
]
exclude = []