"""blog

Revision ID: 9ea543f45877
Revises: 816e1e7f1443
Create Date: 2021-10-23 08:54:34.985117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ea543f45877"
down_revision = "816e1e7f1443"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
