
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-08T00:31:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "194a34a1cfe2f83aea3e5fcb02058ca1b3f4af8b",
 "version": "v1.0.0rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
