[tool.poetry]
name = "safety-road-mapping"
version = "0.1.7"
description = "Module to generate a safety score for brazilian roads."
authors = ["Gabriel Aparecido Fonseca"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/cervejaria-ambev/safety_road_mapping"
repository = "https://github.com/cervejaria-ambev/safety_road_mapping"
keywords = ["geopy", "safety", "folium"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: GIS",
    "Programming Language :: Python :: 3.8",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
folium = "^0.12.1"
openrouteservice = "^2.3.3"
pandas = "^1.3.2"
geopy = "^2.2.0"
python-dotenv = "^0.19.0"
patool = "^1.12"
plotly = "^5.2.2"
Unidecode = "^1.2.0"
colour = "^0.1.5"
typeguard = "^2.12.1"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"
bs4 = "^0.0.1"
flake8 = "^3.9.2"
wget = "^3.2"
pyunpack = "^0.2.2"
pdoc3 = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
