
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-10T13:45:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b341b8794e14955d2296158d3675b0bf5d59ed4",
 "version": "1.15.0.post.dev472"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
