# coding: utf-8

"""
    BAPP API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bapp_api_client.configuration import Configuration


class ProductLocationPrice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'product': 'int',
        'location': 'int',
        'price': 'str',
        'percent_modification': 'str'
    }

    attribute_map = {
        'id': 'id',
        'product': 'product',
        'location': 'location',
        'price': 'price',
        'percent_modification': 'percent_modification'
    }

    def __init__(self, id=None, product=None, location=None, price=None, percent_modification=None, _configuration=None):  # noqa: E501
        """ProductLocationPrice - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._product = None
        self._location = None
        self._price = None
        self._percent_modification = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.product = product
        self.location = location
        self.price = price
        if percent_modification is not None:
            self.percent_modification = percent_modification

    @property
    def id(self):
        """Gets the id of this ProductLocationPrice.  # noqa: E501


        :return: The id of this ProductLocationPrice.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductLocationPrice.


        :param id: The id of this ProductLocationPrice.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def product(self):
        """Gets the product of this ProductLocationPrice.  # noqa: E501


        :return: The product of this ProductLocationPrice.  # noqa: E501
        :rtype: int
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this ProductLocationPrice.


        :param product: The product of this ProductLocationPrice.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and product is None:
            raise ValueError("Invalid value for `product`, must not be `None`")  # noqa: E501

        self._product = product

    @property
    def location(self):
        """Gets the location of this ProductLocationPrice.  # noqa: E501


        :return: The location of this ProductLocationPrice.  # noqa: E501
        :rtype: int
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this ProductLocationPrice.


        :param location: The location of this ProductLocationPrice.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def price(self):
        """Gets the price of this ProductLocationPrice.  # noqa: E501


        :return: The price of this ProductLocationPrice.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ProductLocationPrice.


        :param price: The price of this ProductLocationPrice.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def percent_modification(self):
        """Gets the percent_modification of this ProductLocationPrice.  # noqa: E501

        Dacă doriți să adăugați la preț, setați o valoare pozitivă sau reduceți valoarea negativă  # noqa: E501

        :return: The percent_modification of this ProductLocationPrice.  # noqa: E501
        :rtype: str
        """
        return self._percent_modification

    @percent_modification.setter
    def percent_modification(self, percent_modification):
        """Sets the percent_modification of this ProductLocationPrice.

        Dacă doriți să adăugați la preț, setați o valoare pozitivă sau reduceți valoarea negativă  # noqa: E501

        :param percent_modification: The percent_modification of this ProductLocationPrice.  # noqa: E501
        :type: str
        """

        self._percent_modification = percent_modification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductLocationPrice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductLocationPrice):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProductLocationPrice):
            return True

        return self.to_dict() != other.to_dict()
