# Generated by Django 2.2.11 on 2021-10-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_designer', '0004_auto_20211019_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patternrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='patternrelation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='patternrelation',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='patternrelation',
            name='table_field',
        ),
        migrations.RemoveField(
            model_name='patternrelation',
            name='target',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='patternfield',
            name='relation',
        ),
        migrations.DeleteModel(
            name='PatternFilter',
        ),
        migrations.DeleteModel(
            name='PatternRelation',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
