[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "epimetheus"
authors = [{name = "neumond", email = "knifeslaughter@gmail.com"}]
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.7"
dynamic = ["version", "description"]
dependencies = [
    "attrs",
    "cached-property",
    "sortedcontainers",
]

[project.urls]
Home = "https://github.com/neumond/epimetheus"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-freezegun",
    "pytest-mock",
]
