#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['epimetheus']

package_data = \
{'': ['*']}

install_requires = \
['attrs', 'cached-property', 'sortedcontainers']

extras_require = \
{'test': ['pytest', 'pytest-freezegun', 'pytest-mock']}

setup(name='epimetheus',
      version='0.3.2',
      description='Simplified prometheus client library',
      author=None,
      author_email='neumond <knifeslaughter@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
