[tool.poetry]
name = "deez_stats"
version = "0.2.9"
description = "Python bindings to access competitive league stats."
authors = ["bradyte <bradyte@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
objectpath = "^0.6.1"
yahoo-fantasy-api = "2.4.1"
yahoo-oauth = "^1.1"
numpy = "^1.21.4"
pandas = "^1.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
