
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-08T12:53:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f71917c945aa6b2b99f8de7a0bd4f6b731de2bf",
 "version": "1.15.0.post.dev411"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
