# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

python:
  - 3.6
  - 3.7

install:
  - pip install codecov
  - pip install pytest-cov
  - pip install -r requirements.txt

script:
  - pytest --cov=handypy tests

# Push the results back to codecov
after_success:
  - codecov