
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-08T17:00:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "73175bf98acf8c1112031472947140aa4df062e5",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
