from .decorators import discover_model
from .decorators import discover_project
from .decorators import discover_trained_model
from .projects import parse_input_path
from .projects import parse_input_project_name
from .projects import parse_input_resource_group
from .projects import parse_input_service_connection
from .projects import parse_input_subscription_id
from .projects import parse_input_webapp_kind
from .projects import parse_input_workspace_name
