
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T21:42:04+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "b56af9edc2d84e4f0c37d8274bc1ee4c4d92365c",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
