[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[project]
name = "discrust"
dependencies = ["numpy>=1.21", "pandas>=1.3"]
readme = "README.md"

[project.urls]
repository = "https://github.com/jinlow/discrust"
