VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('08')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('20')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202111081120
version_date = '2021/11/08 11:20'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
