# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")


from . import _ITKLevelSetsPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkLaplacianSegmentationLevelSetImageFilterPython
else:
    import _itkLaplacianSegmentationLevelSetImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkLaplacianSegmentationLevelSetImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkLaplacianSegmentationLevelSetImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import collections.abc
import itk.itkSegmentationLevelSetImageFilterPython
import itk.ITKCommonBasePython
import itk.pyBasePython
import itk.itkImagePython
import itk.itkImageRegionPython
import itk.itkSizePython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkMatrixPython
import itk.itkCovariantVectorPython
import itk.itkFixedArrayPython
import itk.vnl_vector_refPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.itkVectorPython
import itk.vnl_matrix_fixedPython
import itk.itkPointPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkRGBAPixelPython
import itk.itkRGBPixelPython
import itk.itkSegmentationLevelSetFunctionPython
import itk.itkLevelSetFunctionPython
import itk.itkFiniteDifferenceFunctionPython
import itk.itkSparseFieldLevelSetImageFilterPython
import itk.itkFiniteDifferenceImageFilterPython
import itk.itkInPlaceImageFilterAPython
import itk.itkImageToImageFilterAPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterCommonPython
import itk.itkImageToImageFilterBPython

def itkLaplacianSegmentationLevelSetImageFilterID2ID2D_New():
    return itkLaplacianSegmentationLevelSetImageFilterID2ID2D.New()

class itkLaplacianSegmentationLevelSetImageFilterID2ID2D(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterID2ID2D):
    r"""


    Segments structures in images based on a second derivative image
    features.

    IMPORTANT The SegmentationLevelSetImageFilter class and the
    LaplacianSegmentationLevelSetFunction class contain additional
    information necessary to the full understanding of how to use this
    filter. OVERVIEW This class is a level set method segmentation filter.
    It constructs a speed function which is zero at image edges as
    detected by a Laplacian filter. The evolving level set front will
    therefore tend to lock onto zero crossings in the image. The level set
    front moves fastest near edges.

    The Laplacian segmentation filter is intended primarily as a tool for
    refining existing segmentations. The initial isosurface (as given in
    the seed input image) should ideally be very close to the segmentation
    boundary of interest. The idea is that a rough segmentation can be
    refined by allowing the isosurface to deform slightly to achieve a
    better is to refine the output of a hand segmented image.

    Because values in the Laplacian feature image will tend to be low
    except near edge features, this filter is not effective for segmenting
    large image regions from small seed surfaces. INPUTS This filter
    requires two inputs. The first input is a seed image. This seed image
    must contain an isosurface that you want to use as the seed for your
    segmentation. It can be a binary, graylevel, or floating point image.
    The only requirement is that it contain a closed isosurface that you
    will identify as the seed by setting the IsosurfaceValue parameter of
    the filter. For a binary image you will want to set your isosurface
    value halfway between your on and off values (i.e. for 0's and 1's,
    use an isosurface value of 0.5).

    The second input is the feature image. This is the image from which
    the speed function will be calculated. For most applications, this is
    the image that you want to segment. The desired isosurface in your
    seed image should lie within the region of your feature image that you
    are trying to segment.  Note that this filter does no preprocessing of
    the feature image before thresholding. Because second derivative
    calculations are highly sensitive to noise, isotropic or anisotropic
    smoothing of the feature image can dramatically improve the results.

    See SegmentationLevelSetImageFilter for more information on Inputs.
    OUTPUTS The filter outputs a single, scalar, real-valued image.
    Positive *values in the output image are inside the segmented region
    and negative *values in the image are outside of the inside region.
    The zero crossings of *the image correspond to the position of the
    level set front.

    See SparseFieldLevelSetImageFilter and SegmentationLevelSetImageFilter
    for more information. PARAMETERS This filter has no parameters other
    than those described in SegmentationLevelSetImageFilter.

    See:   SegmentationLevelSetImageFilter

    See:  LaplacianSegmentationLevelSetFunction,

    See:   SparseFieldLevelSetImageFilter 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID2ID2D___New_orig__)
    Clone = _swig_new_instance_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID2ID2D_Clone)
    __swig_destroy__ = _itkLaplacianSegmentationLevelSetImageFilterPython.delete_itkLaplacianSegmentationLevelSetImageFilterID2ID2D
    cast = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID2ID2D_cast)

    def New(*args, **kargs):
        """New() -> itkLaplacianSegmentationLevelSetImageFilterID2ID2D

        Create a new object of the class itkLaplacianSegmentationLevelSetImageFilterID2ID2D and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLaplacianSegmentationLevelSetImageFilterID2ID2D.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLaplacianSegmentationLevelSetImageFilterID2ID2D.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLaplacianSegmentationLevelSetImageFilterID2ID2D.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLaplacianSegmentationLevelSetImageFilterID2ID2D in _itkLaplacianSegmentationLevelSetImageFilterPython:
_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID2ID2D_swigregister(itkLaplacianSegmentationLevelSetImageFilterID2ID2D)
itkLaplacianSegmentationLevelSetImageFilterID2ID2D___New_orig__ = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID2ID2D___New_orig__
itkLaplacianSegmentationLevelSetImageFilterID2ID2D_cast = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID2ID2D_cast


def itkLaplacianSegmentationLevelSetImageFilterID3ID3D_New():
    return itkLaplacianSegmentationLevelSetImageFilterID3ID3D.New()

class itkLaplacianSegmentationLevelSetImageFilterID3ID3D(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterID3ID3D):
    r"""


    Segments structures in images based on a second derivative image
    features.

    IMPORTANT The SegmentationLevelSetImageFilter class and the
    LaplacianSegmentationLevelSetFunction class contain additional
    information necessary to the full understanding of how to use this
    filter. OVERVIEW This class is a level set method segmentation filter.
    It constructs a speed function which is zero at image edges as
    detected by a Laplacian filter. The evolving level set front will
    therefore tend to lock onto zero crossings in the image. The level set
    front moves fastest near edges.

    The Laplacian segmentation filter is intended primarily as a tool for
    refining existing segmentations. The initial isosurface (as given in
    the seed input image) should ideally be very close to the segmentation
    boundary of interest. The idea is that a rough segmentation can be
    refined by allowing the isosurface to deform slightly to achieve a
    better is to refine the output of a hand segmented image.

    Because values in the Laplacian feature image will tend to be low
    except near edge features, this filter is not effective for segmenting
    large image regions from small seed surfaces. INPUTS This filter
    requires two inputs. The first input is a seed image. This seed image
    must contain an isosurface that you want to use as the seed for your
    segmentation. It can be a binary, graylevel, or floating point image.
    The only requirement is that it contain a closed isosurface that you
    will identify as the seed by setting the IsosurfaceValue parameter of
    the filter. For a binary image you will want to set your isosurface
    value halfway between your on and off values (i.e. for 0's and 1's,
    use an isosurface value of 0.5).

    The second input is the feature image. This is the image from which
    the speed function will be calculated. For most applications, this is
    the image that you want to segment. The desired isosurface in your
    seed image should lie within the region of your feature image that you
    are trying to segment.  Note that this filter does no preprocessing of
    the feature image before thresholding. Because second derivative
    calculations are highly sensitive to noise, isotropic or anisotropic
    smoothing of the feature image can dramatically improve the results.

    See SegmentationLevelSetImageFilter for more information on Inputs.
    OUTPUTS The filter outputs a single, scalar, real-valued image.
    Positive *values in the output image are inside the segmented region
    and negative *values in the image are outside of the inside region.
    The zero crossings of *the image correspond to the position of the
    level set front.

    See SparseFieldLevelSetImageFilter and SegmentationLevelSetImageFilter
    for more information. PARAMETERS This filter has no parameters other
    than those described in SegmentationLevelSetImageFilter.

    See:   SegmentationLevelSetImageFilter

    See:  LaplacianSegmentationLevelSetFunction,

    See:   SparseFieldLevelSetImageFilter 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID3ID3D___New_orig__)
    Clone = _swig_new_instance_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID3ID3D_Clone)
    __swig_destroy__ = _itkLaplacianSegmentationLevelSetImageFilterPython.delete_itkLaplacianSegmentationLevelSetImageFilterID3ID3D
    cast = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID3ID3D_cast)

    def New(*args, **kargs):
        """New() -> itkLaplacianSegmentationLevelSetImageFilterID3ID3D

        Create a new object of the class itkLaplacianSegmentationLevelSetImageFilterID3ID3D and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLaplacianSegmentationLevelSetImageFilterID3ID3D.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLaplacianSegmentationLevelSetImageFilterID3ID3D.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLaplacianSegmentationLevelSetImageFilterID3ID3D.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLaplacianSegmentationLevelSetImageFilterID3ID3D in _itkLaplacianSegmentationLevelSetImageFilterPython:
_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID3ID3D_swigregister(itkLaplacianSegmentationLevelSetImageFilterID3ID3D)
itkLaplacianSegmentationLevelSetImageFilterID3ID3D___New_orig__ = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID3ID3D___New_orig__
itkLaplacianSegmentationLevelSetImageFilterID3ID3D_cast = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID3ID3D_cast


def itkLaplacianSegmentationLevelSetImageFilterID4ID4D_New():
    return itkLaplacianSegmentationLevelSetImageFilterID4ID4D.New()

class itkLaplacianSegmentationLevelSetImageFilterID4ID4D(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterID4ID4D):
    r"""


    Segments structures in images based on a second derivative image
    features.

    IMPORTANT The SegmentationLevelSetImageFilter class and the
    LaplacianSegmentationLevelSetFunction class contain additional
    information necessary to the full understanding of how to use this
    filter. OVERVIEW This class is a level set method segmentation filter.
    It constructs a speed function which is zero at image edges as
    detected by a Laplacian filter. The evolving level set front will
    therefore tend to lock onto zero crossings in the image. The level set
    front moves fastest near edges.

    The Laplacian segmentation filter is intended primarily as a tool for
    refining existing segmentations. The initial isosurface (as given in
    the seed input image) should ideally be very close to the segmentation
    boundary of interest. The idea is that a rough segmentation can be
    refined by allowing the isosurface to deform slightly to achieve a
    better is to refine the output of a hand segmented image.

    Because values in the Laplacian feature image will tend to be low
    except near edge features, this filter is not effective for segmenting
    large image regions from small seed surfaces. INPUTS This filter
    requires two inputs. The first input is a seed image. This seed image
    must contain an isosurface that you want to use as the seed for your
    segmentation. It can be a binary, graylevel, or floating point image.
    The only requirement is that it contain a closed isosurface that you
    will identify as the seed by setting the IsosurfaceValue parameter of
    the filter. For a binary image you will want to set your isosurface
    value halfway between your on and off values (i.e. for 0's and 1's,
    use an isosurface value of 0.5).

    The second input is the feature image. This is the image from which
    the speed function will be calculated. For most applications, this is
    the image that you want to segment. The desired isosurface in your
    seed image should lie within the region of your feature image that you
    are trying to segment.  Note that this filter does no preprocessing of
    the feature image before thresholding. Because second derivative
    calculations are highly sensitive to noise, isotropic or anisotropic
    smoothing of the feature image can dramatically improve the results.

    See SegmentationLevelSetImageFilter for more information on Inputs.
    OUTPUTS The filter outputs a single, scalar, real-valued image.
    Positive *values in the output image are inside the segmented region
    and negative *values in the image are outside of the inside region.
    The zero crossings of *the image correspond to the position of the
    level set front.

    See SparseFieldLevelSetImageFilter and SegmentationLevelSetImageFilter
    for more information. PARAMETERS This filter has no parameters other
    than those described in SegmentationLevelSetImageFilter.

    See:   SegmentationLevelSetImageFilter

    See:  LaplacianSegmentationLevelSetFunction,

    See:   SparseFieldLevelSetImageFilter 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID4ID4D___New_orig__)
    Clone = _swig_new_instance_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID4ID4D_Clone)
    __swig_destroy__ = _itkLaplacianSegmentationLevelSetImageFilterPython.delete_itkLaplacianSegmentationLevelSetImageFilterID4ID4D
    cast = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID4ID4D_cast)

    def New(*args, **kargs):
        """New() -> itkLaplacianSegmentationLevelSetImageFilterID4ID4D

        Create a new object of the class itkLaplacianSegmentationLevelSetImageFilterID4ID4D and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLaplacianSegmentationLevelSetImageFilterID4ID4D.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLaplacianSegmentationLevelSetImageFilterID4ID4D.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLaplacianSegmentationLevelSetImageFilterID4ID4D.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLaplacianSegmentationLevelSetImageFilterID4ID4D in _itkLaplacianSegmentationLevelSetImageFilterPython:
_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID4ID4D_swigregister(itkLaplacianSegmentationLevelSetImageFilterID4ID4D)
itkLaplacianSegmentationLevelSetImageFilterID4ID4D___New_orig__ = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID4ID4D___New_orig__
itkLaplacianSegmentationLevelSetImageFilterID4ID4D_cast = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterID4ID4D_cast


def itkLaplacianSegmentationLevelSetImageFilterIF2IF2F_New():
    return itkLaplacianSegmentationLevelSetImageFilterIF2IF2F.New()

class itkLaplacianSegmentationLevelSetImageFilterIF2IF2F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF2IF2F):
    r"""


    Segments structures in images based on a second derivative image
    features.

    IMPORTANT The SegmentationLevelSetImageFilter class and the
    LaplacianSegmentationLevelSetFunction class contain additional
    information necessary to the full understanding of how to use this
    filter. OVERVIEW This class is a level set method segmentation filter.
    It constructs a speed function which is zero at image edges as
    detected by a Laplacian filter. The evolving level set front will
    therefore tend to lock onto zero crossings in the image. The level set
    front moves fastest near edges.

    The Laplacian segmentation filter is intended primarily as a tool for
    refining existing segmentations. The initial isosurface (as given in
    the seed input image) should ideally be very close to the segmentation
    boundary of interest. The idea is that a rough segmentation can be
    refined by allowing the isosurface to deform slightly to achieve a
    better is to refine the output of a hand segmented image.

    Because values in the Laplacian feature image will tend to be low
    except near edge features, this filter is not effective for segmenting
    large image regions from small seed surfaces. INPUTS This filter
    requires two inputs. The first input is a seed image. This seed image
    must contain an isosurface that you want to use as the seed for your
    segmentation. It can be a binary, graylevel, or floating point image.
    The only requirement is that it contain a closed isosurface that you
    will identify as the seed by setting the IsosurfaceValue parameter of
    the filter. For a binary image you will want to set your isosurface
    value halfway between your on and off values (i.e. for 0's and 1's,
    use an isosurface value of 0.5).

    The second input is the feature image. This is the image from which
    the speed function will be calculated. For most applications, this is
    the image that you want to segment. The desired isosurface in your
    seed image should lie within the region of your feature image that you
    are trying to segment.  Note that this filter does no preprocessing of
    the feature image before thresholding. Because second derivative
    calculations are highly sensitive to noise, isotropic or anisotropic
    smoothing of the feature image can dramatically improve the results.

    See SegmentationLevelSetImageFilter for more information on Inputs.
    OUTPUTS The filter outputs a single, scalar, real-valued image.
    Positive *values in the output image are inside the segmented region
    and negative *values in the image are outside of the inside region.
    The zero crossings of *the image correspond to the position of the
    level set front.

    See SparseFieldLevelSetImageFilter and SegmentationLevelSetImageFilter
    for more information. PARAMETERS This filter has no parameters other
    than those described in SegmentationLevelSetImageFilter.

    See:   SegmentationLevelSetImageFilter

    See:  LaplacianSegmentationLevelSetFunction,

    See:   SparseFieldLevelSetImageFilter 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF2IF2F___New_orig__)
    Clone = _swig_new_instance_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF2IF2F_Clone)
    __swig_destroy__ = _itkLaplacianSegmentationLevelSetImageFilterPython.delete_itkLaplacianSegmentationLevelSetImageFilterIF2IF2F
    cast = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF2IF2F_cast)

    def New(*args, **kargs):
        """New() -> itkLaplacianSegmentationLevelSetImageFilterIF2IF2F

        Create a new object of the class itkLaplacianSegmentationLevelSetImageFilterIF2IF2F and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLaplacianSegmentationLevelSetImageFilterIF2IF2F.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLaplacianSegmentationLevelSetImageFilterIF2IF2F.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLaplacianSegmentationLevelSetImageFilterIF2IF2F.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLaplacianSegmentationLevelSetImageFilterIF2IF2F in _itkLaplacianSegmentationLevelSetImageFilterPython:
_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF2IF2F_swigregister(itkLaplacianSegmentationLevelSetImageFilterIF2IF2F)
itkLaplacianSegmentationLevelSetImageFilterIF2IF2F___New_orig__ = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF2IF2F___New_orig__
itkLaplacianSegmentationLevelSetImageFilterIF2IF2F_cast = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF2IF2F_cast


def itkLaplacianSegmentationLevelSetImageFilterIF3IF3F_New():
    return itkLaplacianSegmentationLevelSetImageFilterIF3IF3F.New()

class itkLaplacianSegmentationLevelSetImageFilterIF3IF3F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF3IF3F):
    r"""


    Segments structures in images based on a second derivative image
    features.

    IMPORTANT The SegmentationLevelSetImageFilter class and the
    LaplacianSegmentationLevelSetFunction class contain additional
    information necessary to the full understanding of how to use this
    filter. OVERVIEW This class is a level set method segmentation filter.
    It constructs a speed function which is zero at image edges as
    detected by a Laplacian filter. The evolving level set front will
    therefore tend to lock onto zero crossings in the image. The level set
    front moves fastest near edges.

    The Laplacian segmentation filter is intended primarily as a tool for
    refining existing segmentations. The initial isosurface (as given in
    the seed input image) should ideally be very close to the segmentation
    boundary of interest. The idea is that a rough segmentation can be
    refined by allowing the isosurface to deform slightly to achieve a
    better is to refine the output of a hand segmented image.

    Because values in the Laplacian feature image will tend to be low
    except near edge features, this filter is not effective for segmenting
    large image regions from small seed surfaces. INPUTS This filter
    requires two inputs. The first input is a seed image. This seed image
    must contain an isosurface that you want to use as the seed for your
    segmentation. It can be a binary, graylevel, or floating point image.
    The only requirement is that it contain a closed isosurface that you
    will identify as the seed by setting the IsosurfaceValue parameter of
    the filter. For a binary image you will want to set your isosurface
    value halfway between your on and off values (i.e. for 0's and 1's,
    use an isosurface value of 0.5).

    The second input is the feature image. This is the image from which
    the speed function will be calculated. For most applications, this is
    the image that you want to segment. The desired isosurface in your
    seed image should lie within the region of your feature image that you
    are trying to segment.  Note that this filter does no preprocessing of
    the feature image before thresholding. Because second derivative
    calculations are highly sensitive to noise, isotropic or anisotropic
    smoothing of the feature image can dramatically improve the results.

    See SegmentationLevelSetImageFilter for more information on Inputs.
    OUTPUTS The filter outputs a single, scalar, real-valued image.
    Positive *values in the output image are inside the segmented region
    and negative *values in the image are outside of the inside region.
    The zero crossings of *the image correspond to the position of the
    level set front.

    See SparseFieldLevelSetImageFilter and SegmentationLevelSetImageFilter
    for more information. PARAMETERS This filter has no parameters other
    than those described in SegmentationLevelSetImageFilter.

    See:   SegmentationLevelSetImageFilter

    See:  LaplacianSegmentationLevelSetFunction,

    See:   SparseFieldLevelSetImageFilter 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF3IF3F___New_orig__)
    Clone = _swig_new_instance_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF3IF3F_Clone)
    __swig_destroy__ = _itkLaplacianSegmentationLevelSetImageFilterPython.delete_itkLaplacianSegmentationLevelSetImageFilterIF3IF3F
    cast = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF3IF3F_cast)

    def New(*args, **kargs):
        """New() -> itkLaplacianSegmentationLevelSetImageFilterIF3IF3F

        Create a new object of the class itkLaplacianSegmentationLevelSetImageFilterIF3IF3F and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLaplacianSegmentationLevelSetImageFilterIF3IF3F.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLaplacianSegmentationLevelSetImageFilterIF3IF3F.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLaplacianSegmentationLevelSetImageFilterIF3IF3F.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLaplacianSegmentationLevelSetImageFilterIF3IF3F in _itkLaplacianSegmentationLevelSetImageFilterPython:
_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF3IF3F_swigregister(itkLaplacianSegmentationLevelSetImageFilterIF3IF3F)
itkLaplacianSegmentationLevelSetImageFilterIF3IF3F___New_orig__ = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF3IF3F___New_orig__
itkLaplacianSegmentationLevelSetImageFilterIF3IF3F_cast = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF3IF3F_cast


def itkLaplacianSegmentationLevelSetImageFilterIF4IF4F_New():
    return itkLaplacianSegmentationLevelSetImageFilterIF4IF4F.New()

class itkLaplacianSegmentationLevelSetImageFilterIF4IF4F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF4IF4F):
    r"""


    Segments structures in images based on a second derivative image
    features.

    IMPORTANT The SegmentationLevelSetImageFilter class and the
    LaplacianSegmentationLevelSetFunction class contain additional
    information necessary to the full understanding of how to use this
    filter. OVERVIEW This class is a level set method segmentation filter.
    It constructs a speed function which is zero at image edges as
    detected by a Laplacian filter. The evolving level set front will
    therefore tend to lock onto zero crossings in the image. The level set
    front moves fastest near edges.

    The Laplacian segmentation filter is intended primarily as a tool for
    refining existing segmentations. The initial isosurface (as given in
    the seed input image) should ideally be very close to the segmentation
    boundary of interest. The idea is that a rough segmentation can be
    refined by allowing the isosurface to deform slightly to achieve a
    better is to refine the output of a hand segmented image.

    Because values in the Laplacian feature image will tend to be low
    except near edge features, this filter is not effective for segmenting
    large image regions from small seed surfaces. INPUTS This filter
    requires two inputs. The first input is a seed image. This seed image
    must contain an isosurface that you want to use as the seed for your
    segmentation. It can be a binary, graylevel, or floating point image.
    The only requirement is that it contain a closed isosurface that you
    will identify as the seed by setting the IsosurfaceValue parameter of
    the filter. For a binary image you will want to set your isosurface
    value halfway between your on and off values (i.e. for 0's and 1's,
    use an isosurface value of 0.5).

    The second input is the feature image. This is the image from which
    the speed function will be calculated. For most applications, this is
    the image that you want to segment. The desired isosurface in your
    seed image should lie within the region of your feature image that you
    are trying to segment.  Note that this filter does no preprocessing of
    the feature image before thresholding. Because second derivative
    calculations are highly sensitive to noise, isotropic or anisotropic
    smoothing of the feature image can dramatically improve the results.

    See SegmentationLevelSetImageFilter for more information on Inputs.
    OUTPUTS The filter outputs a single, scalar, real-valued image.
    Positive *values in the output image are inside the segmented region
    and negative *values in the image are outside of the inside region.
    The zero crossings of *the image correspond to the position of the
    level set front.

    See SparseFieldLevelSetImageFilter and SegmentationLevelSetImageFilter
    for more information. PARAMETERS This filter has no parameters other
    than those described in SegmentationLevelSetImageFilter.

    See:   SegmentationLevelSetImageFilter

    See:  LaplacianSegmentationLevelSetFunction,

    See:   SparseFieldLevelSetImageFilter 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF4IF4F___New_orig__)
    Clone = _swig_new_instance_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF4IF4F_Clone)
    __swig_destroy__ = _itkLaplacianSegmentationLevelSetImageFilterPython.delete_itkLaplacianSegmentationLevelSetImageFilterIF4IF4F
    cast = _swig_new_static_method(_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF4IF4F_cast)

    def New(*args, **kargs):
        """New() -> itkLaplacianSegmentationLevelSetImageFilterIF4IF4F

        Create a new object of the class itkLaplacianSegmentationLevelSetImageFilterIF4IF4F and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLaplacianSegmentationLevelSetImageFilterIF4IF4F.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLaplacianSegmentationLevelSetImageFilterIF4IF4F.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLaplacianSegmentationLevelSetImageFilterIF4IF4F.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLaplacianSegmentationLevelSetImageFilterIF4IF4F in _itkLaplacianSegmentationLevelSetImageFilterPython:
_itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF4IF4F_swigregister(itkLaplacianSegmentationLevelSetImageFilterIF4IF4F)
itkLaplacianSegmentationLevelSetImageFilterIF4IF4F___New_orig__ = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF4IF4F___New_orig__
itkLaplacianSegmentationLevelSetImageFilterIF4IF4F_cast = _itkLaplacianSegmentationLevelSetImageFilterPython.itkLaplacianSegmentationLevelSetImageFilterIF4IF4F_cast


from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def laplacian_segmentation_level_set_image_filter(*args: itkt.ImageLike,  maximum_iterations: int=..., feature_image: itkt.Image=..., initial_image: itkt.Image=..., speed_image: itkt.Image=..., advection_image: itkt.Image=..., use_negative_features: bool=..., reverse_expansion_direction: bool=..., auto_generate_speed_advection: bool=..., feature_scaling: float=..., propagation_scaling: float=..., advection_scaling: float=..., curvature_scaling: float=..., use_minimal_curvature: bool=..., segmentation_function=..., maximum_curvature_time_step: float=..., maximum_propagation_time_step: float=..., number_of_layers: int=..., iso_surface_value: float=..., interpolate_surface_location: bool=..., difference_function=..., number_of_iterations: int=..., use_image_spacing: bool=..., maximum_rms_error: float=..., rms_change: float=..., manual_reinitialization: bool=..., is_initialized: bool=...,**kwargs)-> itkt.ImageSourceReturn:
    """Functional interface for LaplacianSegmentationLevelSetImageFilter"""
    import itk

    kwarg_typehints = { 'maximum_iterations':maximum_iterations,'feature_image':feature_image,'initial_image':initial_image,'speed_image':speed_image,'advection_image':advection_image,'use_negative_features':use_negative_features,'reverse_expansion_direction':reverse_expansion_direction,'auto_generate_speed_advection':auto_generate_speed_advection,'feature_scaling':feature_scaling,'propagation_scaling':propagation_scaling,'advection_scaling':advection_scaling,'curvature_scaling':curvature_scaling,'use_minimal_curvature':use_minimal_curvature,'segmentation_function':segmentation_function,'maximum_curvature_time_step':maximum_curvature_time_step,'maximum_propagation_time_step':maximum_propagation_time_step,'number_of_layers':number_of_layers,'iso_surface_value':iso_surface_value,'interpolate_surface_location':interpolate_surface_location,'difference_function':difference_function,'number_of_iterations':number_of_iterations,'use_image_spacing':use_image_spacing,'maximum_rms_error':maximum_rms_error,'rms_change':rms_change,'manual_reinitialization':manual_reinitialization,'is_initialized':is_initialized }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)

    instance = itk.LaplacianSegmentationLevelSetImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def laplacian_segmentation_level_set_image_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.ITKLevelSets.LaplacianSegmentationLevelSetImageFilter
    laplacian_segmentation_level_set_image_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    laplacian_segmentation_level_set_image_filter.__doc__ = filter_object.__doc__




