VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('06')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('53')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202111061653
version_date = '2021/11/06 16:53'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
