# Generated by Django 2.2.11 on 2021-08-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, unique=True, verbose_name='Псевдоним')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображение')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Таблица БД',
                'verbose_name_plural': 'Таблицы БД',
                'ordering': ('-pk',),
            },
        ),
    ]
