# Generated by Django 2.2.11 on 2021-10-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_designer', '0007_auto_20211027_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tables',
        ),
    ]
