# Generated by Django 2.2.11 on 2021-11-05 16:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_designer', '0010_reportfield_report_table_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfield',
            name='expression',
        ),
        migrations.AddField(
            model_name='reportfield',
            name='expression_attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Аттрибуты выражения'),
        ),
    ]
