# Generated by Django 3.1.8 on 2021-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_automations', '0004_auto_20210511_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationhookplugin',
            name='operation',
            field=models.IntegerField(choices=[(0, 'Automatisierung starten'), (1, 'Nachricht an Automatisierung'), (2, 'Nachrichten-Broadcast an alle Automatisierungen')], default=1, verbose_name='Kommando'),
        ),
        migrations.AlterField(
            model_name='automationtasksplugin',
            name='always_inform',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert wird das Plugin nichts anzeigen, wenn keine Aufgabe verfügbar ist.', verbose_name='Immer informieren'),
        ),
    ]
