# Generated by Django 2.2.11 on 2021-10-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_designer', '0002_auto_20210831_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='patterns', to='report_designer.PatternGroup', verbose_name='Группы шаблонов'),
        ),
    ]
