
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-07T08:53:58+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "c5d85153a594eb0550cfeef9035d4af1845e943d",
 "version": "3.7.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
