VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('09')
VERSION_HOUR = int('19')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 1
MINOR_VERSION = 5
PATCH_VERSION = 202111091934
version_date = '2021/11/09 19:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
