
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T18:42:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8f6be16a76f0d866750eebc6e972dbad7bd676a",
 "version": "v1.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
