[tool.poetry]
name = "obswebsocket-trio"
version = "0.1.1post2"
description = "Python library to communicate with an obs-websocket server, trio async version. Fork of obs-websocket-py<https://github.com/Elektordi/obs-websocket-py>"
authors = ["Michael D. M. Dryden <mk.dryden@utoronto.ca>"]
repository = "https://github.com/mkdryden/obs-websocket-py-trio"
readme = "README.md"
include = ["samples/*", "CHANGELOG.rst"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
single-source = "^0.2.0"
trio = "^0.19.0"
trio-websocket = "^0.9.2"
six = "^1.16.0"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
