# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/test-scripted-build-pipeline/couchbase-python-client/couchbase_version.py
# at
#    2021-11-03 21:35:54.147815
__version__ = '3.2.3'