
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-10T08:33:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ea920b25586fb1a181d43f1c259218ae85075d7",
 "version": "1.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
