[tool.poetry]
name = "entity"
version = "0.1.0"
description = ""
authors = ["tactik8 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
