
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T14:23:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ad80d0f54918290eff1acc84c6d61e807c66b01",
 "version": "0.3.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
