
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T21:46:38+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "82b3982ae92fc89e80f977ba2966a127c971938b",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
