VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('10')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('49')
MAJOR_VERSION = 1
MINOR_VERSION = 5
PATCH_VERSION = 202111100749
version_date = '2021/11/10 07:49'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
