#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['qtypes']

package_data = \
{'': ['*'],
 'qtypes': ['examples/*', 'graphics/*', 'styles/*', 'styles/tomorrow-night/*']}

install_requires = \
['toml', 'qtpy', 'pint', 'yaq_traits']

extras_require = \
{'dev': ['black', 'pre-commit']}

setup(name='qtypes',
      version='0.3.0',
      description='Build qt graphical user interfaces out of simple type objects.',
      author='Blaise Thompson',
      author_email='blaise@untzag.com',
      url='https://gitlab.com/yaq/qtypes',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
     )
