[package]
name = "rbdt"
version = "0.0.4-alpha2"
edition = "2018"
readme = "Readme.md"
homepage = "https://knuckleheads.club"
repository = "https://github.com/KnuckleheadsClub/rbdt"
license = "MIT"
description = "rbdt is a python library (written in rust) for parsing robots.txt files for large scale batch processing."
keywords = [ "python", "rust", "parser", "robots.txt", "robots-txt"]

[lib]
name = "rbdt"
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use string_sum;` unless the "rlib" or "lib" crate type is also included, e.g.:
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
itertools = "0.9"
unicode-bom = "1"
deunicode = "1.1.1"
regex = "1"

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]