# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QSettings.ui',
# licensing of 'QSettings.ui' applies.
#
# Created: Sun Feb 21 18:56:18 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(513, 326)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings.sizePolicy().hasHeightForWidth())
        settings.setSizePolicy(sizePolicy)
        settings.setFrameShape(QtWidgets.QFrame.WinPanel)
        settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout = QtWidgets.QGridLayout(settings)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tPointsLabel = QtWidgets.QLabel(settings)
        self.tPointsLabel.setObjectName("tPointsLabel")
        self.gridLayout_4.addWidget(self.tPointsLabel, 3, 0, 1, 1)
        self.tStepLineEdit = QtWidgets.QLineEdit(settings)
        self.tStepLineEdit.setObjectName("tStepLineEdit")
        self.gridLayout_4.addWidget(self.tStepLineEdit, 1, 1, 1, 1)
        self.tStepLabel = QtWidgets.QLabel(settings)
        self.tStepLabel.setObjectName("tStepLabel")
        self.gridLayout_4.addWidget(self.tStepLabel, 1, 0, 1, 1)
        self.tPointsLineEdit = QtWidgets.QLineEdit(settings)
        self.tPointsLineEdit.setObjectName("tPointsLineEdit")
        self.gridLayout_4.addWidget(self.tPointsLineEdit, 3, 1, 1, 1)
        self.tStopLineEdit = QtWidgets.QLineEdit(settings)
        self.tStopLineEdit.setObjectName("tStopLineEdit")
        self.gridLayout_4.addWidget(self.tStopLineEdit, 2, 1, 1, 1)
        self.tStopLabel = QtWidgets.QLabel(settings)
        self.tStopLabel.setObjectName("tStopLabel")
        self.gridLayout_4.addWidget(self.tStopLabel, 2, 0, 1, 1)
        self.tStepUnitLabel = QtWidgets.QLabel(settings)
        self.tStepUnitLabel.setObjectName("tStepUnitLabel")
        self.gridLayout_4.addWidget(self.tStepUnitLabel, 1, 2, 1, 1)
        self.tStopUnitLabel = QtWidgets.QLabel(settings)
        self.tStopUnitLabel.setObjectName("tStopUnitLabel")
        self.gridLayout_4.addWidget(self.tStopUnitLabel, 2, 2, 1, 1)
        self.tPointsUnitLabel = QtWidgets.QLabel(settings)
        self.tPointsUnitLabel.setText("")
        self.tPointsUnitLabel.setObjectName("tPointsUnitLabel")
        self.gridLayout_4.addWidget(self.tPointsUnitLabel, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(settings)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fPointsLineEdit = QtWidgets.QLineEdit(settings)
        self.fPointsLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fPointsLineEdit.setObjectName("fPointsLineEdit")
        self.gridLayout_3.addWidget(self.fPointsLineEdit, 3, 1, 1, 1)
        self.fPointsLabel = QtWidgets.QLabel(settings)
        self.fPointsLabel.setObjectName("fPointsLabel")
        self.gridLayout_3.addWidget(self.fPointsLabel, 3, 0, 1, 1)
        self.numHarmonicsLineEdit = QtWidgets.QLineEdit(settings)
        self.numHarmonicsLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numHarmonicsLineEdit.setObjectName("numHarmonicsLineEdit")
        self.gridLayout_3.addWidget(self.numHarmonicsLineEdit, 2, 1, 1, 1)
        self.f0Label = QtWidgets.QLabel(settings)
        self.f0Label.setObjectName("f0Label")
        self.gridLayout_3.addWidget(self.f0Label, 1, 0, 1, 1)
        self.numHarmonicsLabel = QtWidgets.QLabel(settings)
        self.numHarmonicsLabel.setObjectName("numHarmonicsLabel")
        self.gridLayout_3.addWidget(self.numHarmonicsLabel, 2, 0, 1, 1)
        self.f0LineEdit = QtWidgets.QLineEdit(settings)
        self.f0LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f0LineEdit.setObjectName("f0LineEdit")
        self.gridLayout_3.addWidget(self.f0LineEdit, 1, 1, 1, 1)
        self.f0UnitLabel = QtWidgets.QLabel(settings)
        self.f0UnitLabel.setObjectName("f0UnitLabel")
        self.gridLayout_3.addWidget(self.f0UnitLabel, 1, 2, 1, 1)
        self.numHarmonicsUnitLabel = QtWidgets.QLabel(settings)
        self.numHarmonicsUnitLabel.setObjectName("numHarmonicsUnitLabel")
        self.gridLayout_3.addWidget(self.numHarmonicsUnitLabel, 2, 2, 1, 1)
        self.fPointsUnitLabel = QtWidgets.QLabel(settings)
        self.fPointsUnitLabel.setText("")
        self.fPointsUnitLabel.setObjectName("fPointsUnitLabel")
        self.gridLayout_3.addWidget(self.fPointsUnitLabel, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(settings)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.datagroupLabel = QtWidgets.QLabel(settings)
        self.datagroupLabel.setObjectName("datagroupLabel")
        self.gridLayout_2.addWidget(self.datagroupLabel, 1, 0, 1, 1)
        self.datagroupLineEdit = QtWidgets.QLineEdit(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datagroupLineEdit.sizePolicy().hasHeightForWidth())
        self.datagroupLineEdit.setSizePolicy(sizePolicy)
        self.datagroupLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.datagroupLineEdit.setObjectName("datagroupLineEdit")
        self.gridLayout_2.addWidget(self.datagroupLineEdit, 1, 1, 1, 1)
        self.datasetLabel = QtWidgets.QLabel(settings)
        self.datasetLabel.setObjectName("datasetLabel")
        self.gridLayout_2.addWidget(self.datasetLabel, 2, 0, 1, 1)
        self.datasetLineEdit = QtWidgets.QLineEdit(settings)
        self.datasetLineEdit.setObjectName("datasetLineEdit")
        self.gridLayout_2.addWidget(self.datasetLineEdit, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.triggerDeviceLabel = QtWidgets.QLabel(settings)
        self.triggerDeviceLabel.setObjectName("triggerDeviceLabel")
        self.gridLayout_5.addWidget(self.triggerDeviceLabel, 3, 0, 1, 1)
        self.triggerPortSpinBox = QtWidgets.QSpinBox(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerPortSpinBox.sizePolicy().hasHeightForWidth())
        self.triggerPortSpinBox.setSizePolicy(sizePolicy)
        self.triggerPortSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.triggerPortSpinBox.setMinimum(1)
        self.triggerPortSpinBox.setObjectName("triggerPortSpinBox")
        self.gridLayout_5.addWidget(self.triggerPortSpinBox, 3, 3, 1, 1)
        self.portInstrumentLabel = QtWidgets.QLabel(settings)
        self.portInstrumentLabel.setObjectName("portInstrumentLabel")
        self.gridLayout_5.addWidget(self.portInstrumentLabel, 3, 2, 1, 1)
        self.triggerDeviceComboBox = QtWidgets.QComboBox(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerDeviceComboBox.sizePolicy().hasHeightForWidth())
        self.triggerDeviceComboBox.setSizePolicy(sizePolicy)
        self.triggerDeviceComboBox.setObjectName("triggerDeviceComboBox")
        self.gridLayout_5.addWidget(self.triggerDeviceComboBox, 3, 1, 1, 1)
        self.triggerLabel = QtWidgets.QLabel(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerLabel.sizePolicy().hasHeightForWidth())
        self.triggerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.triggerLabel.setFont(font)
        self.triggerLabel.setObjectName("triggerLabel")
        self.gridLayout_5.addWidget(self.triggerLabel, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 2)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        settings.setWindowTitle(QtWidgets.QApplication.translate("settings", "Frame", None, -1))
        self.tPointsLabel.setText(QtWidgets.QApplication.translate("settings", "t_points:", None, -1))
        self.tStepLabel.setText(QtWidgets.QApplication.translate("settings", "t_step:", None, -1))
        self.tStopLabel.setText(QtWidgets.QApplication.translate("settings", "t_stop:", None, -1))
        self.tStepUnitLabel.setText(QtWidgets.QApplication.translate("settings", "s", None, -1))
        self.tStopUnitLabel.setText(QtWidgets.QApplication.translate("settings", "s", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("settings", "Time Sweep", None, -1))
        self.fPointsLabel.setText(QtWidgets.QApplication.translate("settings", "f_points:", None, -1))
        self.f0Label.setText(QtWidgets.QApplication.translate("settings", "f0:", None, -1))
        self.numHarmonicsLabel.setText(QtWidgets.QApplication.translate("settings", "num_harmonics:", None, -1))
        self.f0UnitLabel.setText(QtWidgets.QApplication.translate("settings", "Hz", None, -1))
        self.numHarmonicsUnitLabel.setText(QtWidgets.QApplication.translate("settings", "Hz", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("settings", "Frequency Sweep", None, -1))
        self.datagroupLabel.setText(QtWidgets.QApplication.translate("settings", "datagroup:", None, -1))
        self.datasetLabel.setText(QtWidgets.QApplication.translate("settings", "dataset:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("settings", "Dataset", None, -1))
        self.triggerDeviceLabel.setText(QtWidgets.QApplication.translate("settings", "Device:", None, -1))
        self.portInstrumentLabel.setText(QtWidgets.QApplication.translate("settings", "Port:", None, -1))
        self.triggerLabel.setText(QtWidgets.QApplication.translate("settings", "Trigger", None, -1))

