# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['sila2lib_implementations',
 'sila2lib_implementations.BioREACTOR48',
 'sila2lib_implementations.BioREACTOR48.BioREACTOR48Service',
 'sila2lib_implementations.BioREACTOR48.BioREACTOR48Service.DeviceServicer',
 'sila2lib_implementations.BioREACTOR48.BioREACTOR48Service.DeviceServicer.gRPC',
 'sila2lib_implementations.BioREACTOR48.BioREACTOR48Service.MotorServicer',
 'sila2lib_implementations.BioREACTOR48.BioREACTOR48Service.MotorServicer.gRPC',
 'sila2lib_implementations.BioREACTOR48.BioREACTOR48Service.meta',
 'sila2lib_implementations.BioREACTOR48.lib',
 'sila2lib_implementations.BioREACTOR48.method',
 'sila2lib_implementations.BlueVary',
 'sila2lib_implementations.BlueVary.BlueVaryService',
 'sila2lib_implementations.BlueVary.BlueVaryService.CalibrationServicer',
 'sila2lib_implementations.BlueVary.BlueVaryService.CalibrationServicer.gRPC',
 'sila2lib_implementations.BlueVary.BlueVaryService.DeviceServicer',
 'sila2lib_implementations.BlueVary.BlueVaryService.DeviceServicer.gRPC',
 'sila2lib_implementations.BlueVary.BlueVaryService.SensorServicer',
 'sila2lib_implementations.BlueVary.BlueVaryService.SensorServicer.gRPC',
 'sila2lib_implementations.BlueVary.BlueVaryService.meta',
 'sila2lib_implementations.DASGIP',
 'sila2lib_implementations.DASGIP.DASGIPService',
 'sila2lib_implementations.DASGIP.DASGIPService.AgitationServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.AgitationServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.DOServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.DOServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.DeviceServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.DeviceServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.GassingServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.GassingServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.IlluminationServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.IlluminationServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.LevelServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.LevelServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.OffgasServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.OffgasServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.OpcuaClient',
 'sila2lib_implementations.DASGIP.DASGIPService.OverlayServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.OverlayServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.PHServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.PHServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.PressureServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.PressureServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpAServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpAServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpBServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpBServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpCServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpCServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpDServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.PumpDServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.ReactorServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.ReactorServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.RedoxServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.RedoxServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.TemperatureServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.TemperatureServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.TurbidityServicer',
 'sila2lib_implementations.DASGIP.DASGIPService.TurbidityServicer.gRPC',
 'sila2lib_implementations.DASGIP.DASGIPService.meta',
 'sila2lib_implementations.Flowmeter',
 'sila2lib_implementations.Flowmeter.FlowmeterService',
 'sila2lib_implementations.Flowmeter.FlowmeterService.AlarmService',
 'sila2lib_implementations.Flowmeter.FlowmeterService.AlarmService.gRPC',
 'sila2lib_implementations.Flowmeter.FlowmeterService.CalibrationService',
 'sila2lib_implementations.Flowmeter.FlowmeterService.CalibrationService.gRPC',
 'sila2lib_implementations.Flowmeter.FlowmeterService.DeviceService',
 'sila2lib_implementations.Flowmeter.FlowmeterService.DeviceService.gRPC',
 'sila2lib_implementations.Flowmeter.FlowmeterService.FluidDefinitionService',
 'sila2lib_implementations.Flowmeter.FlowmeterService.FluidDefinitionService.gRPC',
 'sila2lib_implementations.Flowmeter.FlowmeterService.MeasurementProvider',
 'sila2lib_implementations.Flowmeter.FlowmeterService.MeasurementProvider.gRPC',
 'sila2lib_implementations.Flowmeter.FlowmeterService.MeasurementSettingsService',
 'sila2lib_implementations.Flowmeter.FlowmeterService.MeasurementSettingsService.gRPC',
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige',
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige.FlowmeterElflowPrestigeService',
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige.FlowmeterElflowPrestigeService.DeviceService',
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige.FlowmeterElflowPrestigeService.DeviceService.gRPC',
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige.FlowmeterElflowPrestigeService.MeasurementService',
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige.FlowmeterElflowPrestigeService.MeasurementService.gRPC',
 'sila2lib_implementations.LAUDA',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService.ControlParameterServicer',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService.ControlParameterServicer.gRPC',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService.DeviceServicer',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService.DeviceServicer.gRPC',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService.TemperatureControlServicer',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService.TemperatureControlServicer.gRPC',
 'sila2lib_implementations.LAUDA.LAUDA_ThermostatService.meta',
 'sila2lib_implementations.MT_Viper_SW',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service.BalanceService',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service.BalanceService.gRPC',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service.DeviceInformationProvider',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service.DeviceInformationProvider.gRPC',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service.DisplayController',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service.DisplayController.gRPC',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old.BalanceService',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old.BalanceService.gRPC',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old.DeviceInformationProvider',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old.DeviceInformationProvider.gRPC',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old.DisplayController',
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old.DisplayController.gRPC',
 'sila2lib_implementations.Presens',
 'sila2lib_implementations.Presens.PresensService',
 'sila2lib_implementations.Presens.PresensService.CalibrationService',
 'sila2lib_implementations.Presens.PresensService.CalibrationService.gRPC',
 'sila2lib_implementations.Presens.PresensService.DeviceService',
 'sila2lib_implementations.Presens.PresensService.DeviceService.gRPC',
 'sila2lib_implementations.Presens.PresensService.SensorProvider',
 'sila2lib_implementations.Presens.PresensService.SensorProvider.gRPC',
 'sila2lib_implementations.Presens.PresensService_old',
 'sila2lib_implementations.Presens.PresensService_old.CalibrationServicer',
 'sila2lib_implementations.Presens.PresensService_old.CalibrationServicer.gRPC',
 'sila2lib_implementations.Presens.PresensService_old.DeviceController',
 'sila2lib_implementations.Presens.PresensService_old.DeviceController.gRPC',
 'sila2lib_implementations.Presens.PresensService_old.DeviceServicer',
 'sila2lib_implementations.Presens.PresensService_old.DeviceServicer.gRPC',
 'sila2lib_implementations.Presens.PresensService_old.SensorProvider',
 'sila2lib_implementations.Presens.PresensService_old.SensorProvider.gRPC',
 'sila2lib_implementations.Presens.PresensService_old.meta',
 'sila2lib_implementations.Presens.lib',
 'sila2lib_implementations.Presens.method',
 'sila2lib_implementations.RegloDC',
 'sila2lib_implementations.RegloDC.RegloDCService',
 'sila2lib_implementations.RegloDC.RegloDCService.CalibrationServicer',
 'sila2lib_implementations.RegloDC.RegloDCService.CalibrationServicer.gRPC',
 'sila2lib_implementations.RegloDC.RegloDCService.DeviceServicer',
 'sila2lib_implementations.RegloDC.RegloDCService.DeviceServicer.gRPC',
 'sila2lib_implementations.RegloDC.RegloDCService.DriveControlServicer',
 'sila2lib_implementations.RegloDC.RegloDCService.DriveControlServicer.gRPC',
 'sila2lib_implementations.RegloDC.RegloDCService.ParameterControlServicer',
 'sila2lib_implementations.RegloDC.RegloDCService.ParameterControlServicer.gRPC',
 'sila2lib_implementations.RegloICC',
 'sila2lib_implementations.RegloICC.RegloICCService',
 'sila2lib_implementations.RegloICC.RegloICCService.CalibrationServicer',
 'sila2lib_implementations.RegloICC.RegloICCService.CalibrationServicer.gRPC',
 'sila2lib_implementations.RegloICC.RegloICCService.ConfigurationServicer',
 'sila2lib_implementations.RegloICC.RegloICCService.ConfigurationServicer.gRPC',
 'sila2lib_implementations.RegloICC.RegloICCService.DeviceServicer',
 'sila2lib_implementations.RegloICC.RegloICCService.DeviceServicer.gRPC',
 'sila2lib_implementations.RegloICC.RegloICCService.DriveControlServicer',
 'sila2lib_implementations.RegloICC.RegloICCService.DriveControlServicer.gRPC',
 'sila2lib_implementations.RegloICC.RegloICCService.ParameterControlServicer',
 'sila2lib_implementations.RegloICC.RegloICCService.ParameterControlServicer.gRPC',
 'sila2lib_implementations.RegloICC.RegloICCService.meta',
 'sila2lib_implementations._framework']

package_data = \
{'': ['*'],
 'sila2lib_implementations.BioREACTOR48': ['BioREACTOR48_project/*'],
 'sila2lib_implementations.BlueVary': ['BlueVary_project/*'],
 'sila2lib_implementations.DASGIP': ['DASGIP_project/*'],
 'sila2lib_implementations.Flowmeter': ['Flowmeter_project/*'],
 'sila2lib_implementations.Flowmeter.FlowmeterService': ['meta/*'],
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige': ['FlowmeterElflowPrestige_project/*'],
 'sila2lib_implementations.Flowmeter_ELFLOWPrestige.FlowmeterElflowPrestigeService': ['meta/*'],
 'sila2lib_implementations.LAUDA': ['LAUDA_project/*'],
 'sila2lib_implementations.MT_Viper_SW': ['MT_Viper_SW_Balance_project/*'],
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service': ['meta/*'],
 'sila2lib_implementations.MT_Viper_SW.MT_Viper_SW_Balance_Service_old': ['meta/*'],
 'sila2lib_implementations.Presens': ['Presens_project/*',
                                      'Presens_project_old/*'],
 'sila2lib_implementations.Presens.PresensService': ['meta/*'],
 'sila2lib_implementations.RegloDC': ['RegloDC_project/*'],
 'sila2lib_implementations.RegloDC.RegloDCService': ['meta/*'],
 'sila2lib_implementations.RegloICC': ['RegloICC_project/*']}

install_requires = \
['psycopg2-binary==2.9.1',
 'pydantic==1.8.2',
 'pyserial==3.5',
 'python-dotenv==0.19.1',
 'sila2lib==0.2.5']

setup_kwargs = {
    'name': 'sila2lib-implementations',
    'version': '0.1.0',
    'description': 'A package of SiLA drivers for various devices at TUM-BVT',
    'long_description': 'Creation date: 20.10.2020, 12:50  \nLast modification: 10.03.2021, 12:52  \nAuthors: Lukas Bromig, Nikolas von den Eichen, Valeryia Sidarava, Jose Jesus de Pina Torres \n\n# sila2lib_implementations\n\nThis repository contains SiLA2 drivers for a variety of device that are being used at the [Chair of Biochemical Engineering](https://www.mw.tum.de/en/biovt/home/) at TUM. The repository is setup in a way that it can be installed as python package. Client files can be imported. \n\nThe following devices are supported:\n- **BlueVary Offgas-analytics**\n- **DASGIP 4xParallel Reactor System**\n- **LAUDA LOOP 250**\n- **LAUDA LOOP 500**\n- **Presens sensor bars**\n- **Reglo ICC peristaltic pump**\n- **Flowmeter Bronkhorst**\n\nSiLA version of drivers may vary. In case of incompatibilities, please reach out to:   \n*lukas.bromig@tum.de* \n\n## Installation\n\nAfter cloning the repository, run the update_package.bat to create the installation files (distribution).  \nThe distribution process will create the respective tar.gz and wheel file in the dist folder.   \n``````\n\nInstallation of the package files:  \nUsing pip:\n```pip install sila2lib_implementations/dist/sila2lib_implementations-Lukas-Bromig-0.0.1.tar.gz``` \n\nUsing pipenv:\npipenv install sila2lib_implementations/dist/sila2lib_implementations-Lukas-Bromig-0.0.1.tar.gz\n\nRequires sila2lib, sila2comlib and [optional] sila2codegenerator for unit tests. \nFurther requirements include:\n- InfluxDB, csv, numpy, persistent, opcua, pyserial, cryptography  \nThese packages can be installed via the pypi index using pip/pipenv install <package_name>.\nMake sure that protobuf is installed with the PIP_NO_BINARY option. This is more complicated when using pipenv. An\nenvironmental variable for PIP_NO_BINARY has to be used. [Refer to documentation](link).\n',
    'author': 'Lukas Bromig',
    'author_email': 'lukas.bromig@tum.de',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://gitlab.com/lukas.bromig/sila2lib_implementations',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '==3.8.10',
}


setup(**setup_kwargs)
