# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phenopackets/schema/v2/core/individual.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .  import base_pb2 as phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='phenopackets/schema/v2/core/individual.proto',
  package='org.phenopackets.schema.v2.core',
  syntax='proto3',
  serialized_options=b'\n\037org.phenopackets.schema.v2.coreP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,phenopackets/schema/v2/core/individual.proto\x12\x1forg.phenopackets.schema.v2.core\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&phenopackets/schema/v2/core/base.proto\"\xf1\x03\n\nIndividual\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\ralternate_ids\x18\x02 \x03(\t\x12\x31\n\rdate_of_birth\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12L\n\x16time_at_last_encounter\x18\x04 \x01(\x0b\x32,.org.phenopackets.schema.v2.core.TimeElement\x12\x42\n\x0cvital_status\x18\x05 \x01(\x0b\x32,.org.phenopackets.schema.v2.core.VitalStatus\x12\x31\n\x03sex\x18\x06 \x01(\x0e\x32$.org.phenopackets.schema.v2.core.Sex\x12\x46\n\x0ekaryotypic_sex\x18\x07 \x01(\x0e\x32..org.phenopackets.schema.v2.core.KaryotypicSex\x12>\n\x06gender\x18\x08 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12@\n\x08taxonomy\x18\t \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\"\xb5\x02\n\x0bVitalStatus\x12\x43\n\x06status\x18\x01 \x01(\x0e\x32\x33.org.phenopackets.schema.v2.core.VitalStatus.Status\x12\x43\n\rtime_of_death\x18\x02 \x01(\x0b\x32,.org.phenopackets.schema.v2.core.TimeElement\x12\x46\n\x0e\x63\x61use_of_death\x18\x03 \x01(\x0b\x32..org.phenopackets.schema.v2.core.OntologyClass\x12\x1d\n\x15survival_time_in_days\x18\x04 \x01(\r\"5\n\x06Status\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\t\n\x05\x41LIVE\x10\x01\x12\x0c\n\x08\x44\x45\x43\x45\x41SED\x10\x02*;\n\x03Sex\x12\x0f\n\x0bUNKNOWN_SEX\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\x08\n\x04MALE\x10\x02\x12\r\n\tOTHER_SEX\x10\x03*\x8c\x01\n\rKaryotypicSex\x12\x15\n\x11UNKNOWN_KARYOTYPE\x10\x00\x12\x06\n\x02XX\x10\x01\x12\x06\n\x02XY\x10\x02\x12\x06\n\x02XO\x10\x03\x12\x07\n\x03XXY\x10\x04\x12\x07\n\x03XXX\x10\x05\x12\x08\n\x04XXYY\x10\x06\x12\x08\n\x04XXXY\x10\x07\x12\x08\n\x04XXXX\x10\x08\x12\x07\n\x03XYY\x10\t\x12\x13\n\x0fOTHER_KARYOTYPE\x10\nB#\n\x1forg.phenopackets.schema.v2.coreP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2.DESCRIPTOR,])

_SEX = _descriptor.EnumDescriptor(
  name='Sex',
  full_name='org.phenopackets.schema.v2.core.Sex',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SEX', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER_SEX', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=966,
  serialized_end=1025,
)
_sym_db.RegisterEnumDescriptor(_SEX)

Sex = enum_type_wrapper.EnumTypeWrapper(_SEX)
_KARYOTYPICSEX = _descriptor.EnumDescriptor(
  name='KaryotypicSex',
  full_name='org.phenopackets.schema.v2.core.KaryotypicSex',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_KARYOTYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XX', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XO', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XXY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XXX', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XXYY', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XXXY', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XXXX', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XYY', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER_KARYOTYPE', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1028,
  serialized_end=1168,
)
_sym_db.RegisterEnumDescriptor(_KARYOTYPICSEX)

KaryotypicSex = enum_type_wrapper.EnumTypeWrapper(_KARYOTYPICSEX)
UNKNOWN_SEX = 0
FEMALE = 1
MALE = 2
OTHER_SEX = 3
UNKNOWN_KARYOTYPE = 0
XX = 1
XY = 2
XO = 3
XXY = 4
XXX = 5
XXYY = 6
XXXY = 7
XXXX = 8
XYY = 9
OTHER_KARYOTYPE = 10


_VITALSTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='org.phenopackets.schema.v2.core.VitalStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DECEASED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=911,
  serialized_end=964,
)
_sym_db.RegisterEnumDescriptor(_VITALSTATUS_STATUS)


_INDIVIDUAL = _descriptor.Descriptor(
  name='Individual',
  full_name='org.phenopackets.schema.v2.core.Individual',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.phenopackets.schema.v2.core.Individual.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alternate_ids', full_name='org.phenopackets.schema.v2.core.Individual.alternate_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_of_birth', full_name='org.phenopackets.schema.v2.core.Individual.date_of_birth', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_at_last_encounter', full_name='org.phenopackets.schema.v2.core.Individual.time_at_last_encounter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vital_status', full_name='org.phenopackets.schema.v2.core.Individual.vital_status', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sex', full_name='org.phenopackets.schema.v2.core.Individual.sex', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='karyotypic_sex', full_name='org.phenopackets.schema.v2.core.Individual.karyotypic_sex', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='org.phenopackets.schema.v2.core.Individual.gender', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taxonomy', full_name='org.phenopackets.schema.v2.core.Individual.taxonomy', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=652,
)


_VITALSTATUS = _descriptor.Descriptor(
  name='VitalStatus',
  full_name='org.phenopackets.schema.v2.core.VitalStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='org.phenopackets.schema.v2.core.VitalStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_of_death', full_name='org.phenopackets.schema.v2.core.VitalStatus.time_of_death', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cause_of_death', full_name='org.phenopackets.schema.v2.core.VitalStatus.cause_of_death', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='survival_time_in_days', full_name='org.phenopackets.schema.v2.core.VitalStatus.survival_time_in_days', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VITALSTATUS_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=964,
)

_INDIVIDUAL.fields_by_name['date_of_birth'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_INDIVIDUAL.fields_by_name['time_at_last_encounter'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._TIMEELEMENT
_INDIVIDUAL.fields_by_name['vital_status'].message_type = _VITALSTATUS
_INDIVIDUAL.fields_by_name['sex'].enum_type = _SEX
_INDIVIDUAL.fields_by_name['karyotypic_sex'].enum_type = _KARYOTYPICSEX
_INDIVIDUAL.fields_by_name['gender'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_INDIVIDUAL.fields_by_name['taxonomy'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_VITALSTATUS.fields_by_name['status'].enum_type = _VITALSTATUS_STATUS
_VITALSTATUS.fields_by_name['time_of_death'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._TIMEELEMENT
_VITALSTATUS.fields_by_name['cause_of_death'].message_type = phenopackets_dot_schema_dot_v2_dot_core_dot_base__pb2._ONTOLOGYCLASS
_VITALSTATUS_STATUS.containing_type = _VITALSTATUS
DESCRIPTOR.message_types_by_name['Individual'] = _INDIVIDUAL
DESCRIPTOR.message_types_by_name['VitalStatus'] = _VITALSTATUS
DESCRIPTOR.enum_types_by_name['Sex'] = _SEX
DESCRIPTOR.enum_types_by_name['KaryotypicSex'] = _KARYOTYPICSEX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Individual = _reflection.GeneratedProtocolMessageType('Individual', (_message.Message,), {
  'DESCRIPTOR' : _INDIVIDUAL,
  '__module__' : 'phenopackets.schema.v2.core.individual_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.Individual)
  })
_sym_db.RegisterMessage(Individual)

VitalStatus = _reflection.GeneratedProtocolMessageType('VitalStatus', (_message.Message,), {
  'DESCRIPTOR' : _VITALSTATUS,
  '__module__' : 'phenopackets.schema.v2.core.individual_pb2'
  # @@protoc_insertion_point(class_scope:org.phenopackets.schema.v2.core.VitalStatus)
  })
_sym_db.RegisterMessage(VitalStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
