
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T05:09:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "664c89bb33769c3d3d6e744b4919879119e422fc",
 "version": "2021.11.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
