[tool.black]
line-length = 100

[tool.poetry]
name = "FAST-OAD"
version = "v1.1.1"
description = "FAST-OAD is a framework for performing rapid Overall Aircraft Design"
readme = "README.md"
authors = [
    "Christophe DAVID <christophe.david@onera.fr>",
    "Scott DELBECQ <Scott.DELBECQ@isae-supaero.fr>"
]
packages = [
    { include = "fastoad", from = "src" },
]
exclude = ["**/tests/**"]

homepage = "https://github.com/fast-aircraft-design/FAST-OAD"
keywords = [
    "aircraft",
    "design",
    "multi-disciplinary"
]
license = "GPL-3.0-only"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering :: Physics"
]

[tool.poetry.dependencies]
# IMPORTANT: when modifying this list, docs/requirements.txt must be updated for
# ReadTheDocs to be able to compile the documentation.
# A pre-commit hook has been added to do this task. As a result, any modification
# of poetry.lock file will modify docs/requirements.txt and make
# the commit fail because "files were modified by this hook". In that case,
# doing again the commit including changes in docs/requirements.txt will succeed.
python = "^3.7"
numpy = "^1.17.3"
scipy = "^1.3.2"
pandas = "^1.1.0"
openmdao = "^3.10"
ipopo = "^1.0.0"
ipywidgets = "^7.3.0"
ipysheet = "^0.4.0"
matplotlib = "^3.1.2"
plotly = "^4.5.0"
wop = "^1.13.1"
lxml = "^4.6.3"
tomlkit = ">=0.5.3 <1"
"ruamel.yaml" = ">=0.15.78 <0.18"
jsonschema = "^3.2.0"
ensure = "^1.0.0"
tabulate = "^0.8.9"
aenum = "^3.1.0"
jupyter-client = "!=7.0.0,!=7.0.1,!=7.0.2,!=7.0.3,!=7.0.4,!=7.0.5"  # v7.0.6 fixes issue #381

jupyterlab = {version = "^2", optional = true}

[tool.poetry.extras]
jupyterlab = ["jupyterlab"]


[tool.poetry.dev-dependencies]
pytest = ">=5.2"
pytest-cov = "*"
pre-commit = "*"
black = { version = "19.10b0", allow-prereleases = true } # if version is changed, please change it also in .pre-commit-config.yaml file.
pylint = "*"
nbval = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
sphinxcontrib-bibtex = "*"

[tool.poetry.scripts]
fastoad = "fastoad.cmd.fast:main"
fast-oad = "fastoad.cmd.fast:main"

[tool.poetry.plugins."fastoad_model"]
"internal_models" = "fastoad.models"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
